<?php
// if( function_exists('acf_add_local_field_group') ):
//     acf_add_local_field_group(array(
//         'key' => 'group_5bf2b42e0d67d',
//         'title' => 'Blocks',
//         'fields' => array(
//             array(
//                 'key' => 'field_5bf2b4d429f3a',
//                 'label' => 'Blocks',
//                 'name' => 'blocks',
//                 'type' => 'flexible_content',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'layouts' => array(
//                     '5bf2b4dfc6e40' => array(
//                         'key' => '5bf2b4dfc6e40',
//                         'name' => 'block_discover',
//                         'label' => 'Discover',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5d42s4g7c7v',
//                                 'label' => 'Content',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5c07db8d8825b',
//                                 'label' => 'Background : color',
//                                 'name' => 'bg_color',
//                                 'type' => 'color_picker',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '33',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5bf2b4ef29f3b',
//                                 'label' => 'Logo',
//                                 'name' => 'logo',
//                                 'type' => 'image',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '33',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                                 'preview_size' => 'thumbnail',
//                                 'library' => 'all',
//                                 'min_width' => '',
//                                 'min_height' => '',
//                                 'min_size' => '',
//                                 'max_width' => '',
//                                 'max_height' => '',
//                                 'max_size' => '',
//                                 'mime_types' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5c8112650ecb1',
//                                 'label' => 'Logo : width (px)',
//                                 'name' => 'logo_width',
//                                 'type' => 'number',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '33',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'min' => '',
//                                 'max' => '',
//                                 'step' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5bf2b45d3b8fc',
//                                 'label' => 'Text',
//                                 'name' => 'wysywyg',
//                                 'type' => 'wysiwyg',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'tabs' => 'all',
//                                 'toolbar' => 'full',
//                                 'media_upload' => 0,
//                                 'delay' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5bf2b47a4708c',
//                                 'label' => 'Discover Link : left',
//                                 'name' => 'link_left',
//                                 'type' => 'link',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '50',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                             ),
//                             array(
//                                 'key' => 'field_5bf2b4a64708d',
//                                 'label' => 'Discover Link : right',
//                                 'name' => 'link_right',
//                                 'type' => 'link',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '50',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                             ),
//                             array(
//                                 'key' => 'field_5d42efdcdf7c7e',
//                                 'label' => 'Animate',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5d42eff2fcd7c7f',
//                                 'label' => 'Animation',
//                                 'name' => 'animation',
//                                 'type' => 'button_group',
//                                 'instructions' => 'Text animation',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'choices' => array(
//                                     'gen' => 'General animation',
//                                     'sfb' => 'Slide from bottom',
//                                     'sft' => 'Slide from top',
//                                     'sfr' => 'Slide from right',
//                                     'sfl' => 'Slide from left',
//                                     'fadein' => 'Fade In',
//                                     'none' => 'No animation',
//                                 ),
//                                 'allow_null' => 0,
//                                 'default_value' => '',
//                                 'layout' => 'horizontal',
//                                 'return_format' => 'value',
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                     '5bf419776d222' => array(
//                         'key' => '5bf419776d222',
//                         'name' => 'block_text',
//                         'label' => 'Text',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5c07dbbd69a82',
//                                 'label' => 'Background : color',
//                                 'name' => 'bg_color',
//                                 'type' => 'color_picker',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5bf419b46d223',
//                                 'label' => 'Text',
//                                 'name' => 'wysywyg',
//                                 'type' => 'wysiwyg',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'tabs' => 'all',
//                                 'toolbar' => 'full',
//                                 'media_upload' => 0,
//                                 'delay' => 0,
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                     '5bf2bcdb4fd35' => array(
//                         'key' => '5bf2bcdb4fd35',
//                         'name' => 'block_background_title',
//                         'label' => 'Background & Title',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5d42s4v7c7z',
//                                 'label' => 'Content',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5bf2bcea4fd36',
//                                 'label' => 'Image : background',
//                                 'name' => 'background',
//                                 'type' => 'image',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                                 'preview_size' => 'thumbnail',
//                                 'library' => 'all',
//                                 'min_width' => '',
//                                 'min_height' => '',
//                                 'min_size' => '',
//                                 'max_width' => '',
//                                 'max_height' => '',
//                                 'max_size' => '',
//                                 'mime_types' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5bf2bd044fd37',
//                                 'label' => 'Title',
//                                 'name' => 'title',
//                                 'type' => 'text',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'maxlength' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d3a0a34058a4',
//                                 'label' => 'Overlay : color',
//                                 'name' => 'overlay_color',
//                                 'type' => 'color_picker',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '50',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '#000000',
//                             ),
//                             array(
//                                 'key' => 'field_5d3a0aa8058a5',
//                                 'label' => 'Overlay : opacity',
//                                 'name' => 'overlay_opacity',
//                                 'type' => 'range',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '50',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'min' => '',
//                                 'max' => 1,
//                                 'step' => '0.1',
//                                 'prepend' => '',
//                                 'append' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d42e4cdf7c7e',
//                                 'label' => 'Animate',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5d42eff2fdd7c7f',
//                                 'label' => 'Animation',
//                                 'name' => 'animation',
//                                 'type' => 'button_group',
//                                 'instructions' => 'Text animation',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'choices' => array(
//                                     'gen' => 'General animation',
//                                     'sfb' => 'Slide from bottom',
//                                     'sft' => 'Slide from top',
//                                     'sfr' => 'Slide from right',
//                                     'sfl' => 'Slide from left',
//                                     'fadein' => 'Fade In',
//                                     'none' => 'No animation',
//                                 ),
//                                 'allow_null' => 0,
//                                 'default_value' => '',
//                                 'layout' => 'horizontal',
//                                 'return_format' => 'value',
//                             ),
//
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                     '5bf3387320165' => array(
//                         'key' => '5bf3387320165',
//                         'name' => 'block_background',
//                         'label' => 'Background ',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5d42x4g7c7z',
//                                 'label' => 'Content',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5bf3388420166',
//                                 'label' => 'Image : background',
//                                 'name' => 'background',
//                                 'type' => 'image',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                                 'preview_size' => 'thumbnail',
//                                 'library' => 'all',
//                                 'min_width' => '',
//                                 'min_height' => '',
//                                 'min_size' => '',
//                                 'max_width' => '',
//                                 'max_height' => '',
//                                 'max_size' => '',
//                                 'mime_types' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5dyydcdf7c7e',
//                                 'label' => 'Animate',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5d42efxx2fcd7c7f',
//                                 'label' => 'Animation',
//                                 'name' => 'animation',
//                                 'type' => 'button_group',
//                                 'instructions' => 'Text animation',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'choices' => array(
//                                     'gen' => 'General animation',
//                                     'sfb' => 'Slide from bottom',
//                                     'sft' => 'Slide from top',
//                                     'sfr' => 'Slide from right',
//                                     'sfl' => 'Slide from left',
//                                     'fadein' => 'Fade In',
//                                     'none' => 'No animation',
//                                 ),
//                                 'allow_null' => 0,
//                                 'default_value' => '',
//                                 'layout' => 'horizontal',
//                                 'return_format' => 'value',
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                     '5bf33a6b6feb7' => array(
//                         'key' => '5bf33a6b6feb7',
//                         'name' => 'block_background_text',
//                         'label' => 'Background & Text',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5d4defddf7c7n',
//                                 'label' => 'Content',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5bf33a7d6feb8',
//                                 'label' => 'Image : background',
//                                 'name' => 'background',
//                                 'type' => 'image',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '33',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                                 'preview_size' => 'thumbnail',
//                                 'library' => 'all',
//                                 'min_width' => '',
//                                 'min_height' => '',
//                                 'min_size' => '',
//                                 'max_width' => '',
//                                 'max_height' => '',
//                                 'max_size' => '',
//                                 'mime_types' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d3a0a34058ag',
//                                 'label' => 'Overlay : color',
//                                 'name' => 'overlay_color',
//                                 'type' => 'color_picker',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '33',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '#000000',
//                             ),
//                             array(
//                                 'key' => 'field_5d3a0aa8058af',
//                                 'label' => 'Overlay : opacity',
//                                 'name' => 'overlay_opacity',
//                                 'type' => 'range',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '33',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'min' => '',
//                                 'max' => 1,
//                                 'step' => '0.1',
//                                 'prepend' => '',
//                                 'append' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5bf33a966feb9',
//                                 'label' => 'Text',
//                                 'name' => 'wysywig',
//                                 'type' => 'wysiwyg',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'tabs' => 'all',
//                                 'toolbar' => 'full',
//                                 'media_upload' => 0,
//                                 'delay' => 0,
//                             ),
//
//                             array(
//                                 'key' => 'field_5dxx2efddf7c7z',
//                                 'label' => 'Animate',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5d42eff2f7c71',
//                                 'label' => 'Animation',
//                                 'name' => 'animation',
//                                 'type' => 'button_group',
//                                 'instructions' => 'Text animation',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'choices' => array(
//                                     '' => 'General animation',
//                                     'sfb' => 'Slide from bottom',
//                                     'sft' => 'Slide from top',
//                                     'sfr' => 'Slide from right',
//                                     'sfl' => 'Slide from left',
//                                     'fadein' => 'Fade In',
//                                     'none' => 'No animation',
//                                 ),
//                                 'allow_null' => 0,
//                                 'default_value' => '',
//                                 'layout' => 'horizontal',
//                                 'return_format' => 'value',
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                     '5bf411e88d6a7' => array(
//                         'key' => '5bf411e88d6a7',
//                         'name' => 'block_logo_text',
//                         'label' => 'Logo & Text',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5dw2s4g7c7z',
//                                 'label' => 'Content',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5c07dbcb69a83',
//                                 'label' => 'Background : color',
//                                 'name' => 'bg_color',
//                                 'type' => 'color_picker',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5bf411fa8d6a8',
//                                 'label' => 'Logo',
//                                 'name' => 'logo',
//                                 'type' => 'image',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '25',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                                 'preview_size' => 'thumbnail',
//                                 'library' => 'all',
//                                 'min_width' => '',
//                                 'min_height' => '',
//                                 'min_size' => '',
//                                 'max_width' => '',
//                                 'max_height' => '',
//                                 'max_size' => '',
//                                 'mime_types' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5bf4120d8d6a9',
//                                 'label' => 'Text',
//                                 'name' => 'wysywyg',
//                                 'type' => 'wysiwyg',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '75',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'tabs' => 'all',
//                                 'toolbar' => 'full',
//                                 'media_upload' => 0,
//                                 'delay' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5dc2efddcdf7c7e',
//                                 'label' => 'Animate',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5da42effrcd7c7f',
//                                 'label' => 'Animation',
//                                 'name' => 'animation',
//                                 'type' => 'button_group',
//                                 'instructions' => 'Text animation',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'choices' => array(
//                                     'gen' => 'General animation',
//                                     'sfb' => 'Slide from bottom',
//                                     'sft' => 'Slide from top',
//                                     'sfr' => 'Slide from right',
//                                     'sfl' => 'Slide from left',
//                                     'fadein' => 'Fade In',
//                                     'none' => 'No animation',
//                                 ),
//                                 'allow_null' => 0,
//                                 'default_value' => '',
//                                 'layout' => 'horizontal',
//                                 'return_format' => 'value',
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                     'layout_5d0b96430bbea' => array(
//                         'key' => 'layout_5d0b96430bbea',
//                         'name' => 'block_image_text',
//                         'label' => 'Image & Text',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5d42efddf7c7n',
//                                 'label' => 'Content',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5d0b96600bbee',
//                                 'label' => 'Layout',
//                                 'name' => 'layout',
//                                 'type' => 'button_group',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '33',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'choices' => array(
//                                     'default' => 'Default',
//                                     'text-75' => 'Text 75%',
//                                     'image-75' => 'Image 75%',
//                                 ),
//                                 'allow_null' => 0,
//                                 'default_value' => 'default',
//                                 'layout' => 'horizontal',
//                                 'return_format' => 'value',
//                             ),
//                             array(
//                                 'key' => 'field_5d0b96cd0bbef',
//                                 'label' => 'Reverse',
//                                 'name' => 'reverse',
//                                 'type' => 'true_false',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '33',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'message' => '',
//                                 'default_value' => 0,
//                                 'ui' => 0,
//                                 'ui_on_text' => '',
//                                 'ui_off_text' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d0b96430bbeb',
//                                 'label' => 'Background : color',
//                                 'name' => 'bg_color',
//                                 'type' => 'color_picker',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '33',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d0b96430bbec',
//                                 'label' => 'Image',
//                                 'name' => 'image',
//                                 'type' => 'image',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '25',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'url',
//                                 'preview_size' => 'thumbnail',
//                                 'library' => 'all',
//                                 'min_width' => '',
//                                 'min_height' => '',
//                                 'min_size' => '',
//                                 'max_width' => '',
//                                 'max_height' => '',
//                                 'max_size' => '',
//                                 'mime_types' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d0b96430bbed',
//                                 'label' => 'Text',
//                                 'name' => 'wysywyg',
//                                 'type' => 'wysiwyg',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '75',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'tabs' => 'all',
//                                 'toolbar' => 'full',
//                                 'media_upload' => 0,
//                                 'delay' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5d42efddf7c7e',
//                                 'label' => 'Animate',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5d42eff2f7c7f',
//                                 'label' => 'Animation',
//                                 'name' => 'animation',
//                                 'type' => 'button_group',
//                                 'instructions' => 'Text animation',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'choices' => array(
//                                     'gen' => 'General animation',
//                                     'sfb' => 'Slide from bottom',
//                                     'sft' => 'Slide from top',
//                                     'sfr' => 'Slide from right',
//                                     'sfl' => 'Slide from left',
//                                     'fadein' => 'Fade In',
//                                     'none' => 'No animation',
//                                 ),
//                                 'allow_null' => 0,
//                                 'default_value' => '',
//                                 'layout' => 'horizontal',
//                                 'return_format' => 'value',
//                             ),
//
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                     'layout_5d0baacc3a0d0' => array(
//                         'key' => 'layout_5d0baacc3a0d0',
//                         'name' => 'block_icons_text',
//                         'label' => 'Icons & Text',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5d42s4g7c7z',
//                                 'label' => 'Content',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5d0baa5a3a0cd',
//                                 'label' => 'Icon : 01',
//                                 'name' => 'icon01_grp',
//                                 'type' => 'group',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '25',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'layout' => 'block',
//                                 'sub_fields' => array(
//                                     array(
//                                         'key' => 'field_5d0baa763a0ce',
//                                         'label' => 'Icon',
//                                         'name' => 'icon',
//                                         'type' => 'image',
//                                         'instructions' => '',
//                                         'required' => 0,
//                                         'conditional_logic' => 0,
//                                         'wrapper' => array(
//                                             'width' => '',
//                                             'class' => '',
//                                             'id' => '',
//                                         ),
//                                         'return_format' => 'array',
//                                         'preview_size' => 'medium',
//                                         'library' => '',
//                                         'min_width' => '',
//                                         'min_height' => '',
//                                         'min_size' => '',
//                                         'max_width' => '',
//                                         'max_height' => '',
//                                         'max_size' => '',
//                                         'mime_types' => '',
//                                     ),
//                                     array(
//                                         'key' => 'field_5d0baab93a0cf',
//                                         'label' => 'Title',
//                                         'name' => 'title',
//                                         'type' => 'text',
//                                         'instructions' => '',
//                                         'required' => 0,
//                                         'conditional_logic' => 0,
//                                         'wrapper' => array(
//                                             'width' => '',
//                                             'class' => '',
//                                             'id' => '',
//                                         ),
//                                         'default_value' => '',
//                                         'placeholder' => '',
//                                         'prepend' => '',
//                                         'append' => '',
//                                         'maxlength' => '',
//                                     ),
//                                 ),
//                             ),
//                             array(
//                                 'key' => 'field_5d0baade3a0d1',
//                                 'label' => 'Icon : 02',
//                                 'name' => 'icon02_grp',
//                                 'type' => 'group',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '25',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'layout' => 'block',
//                                 'sub_fields' => array(
//                                     array(
//                                         'key' => 'field_5d0baade3a0d2',
//                                         'label' => 'Icon',
//                                         'name' => 'icon',
//                                         'type' => 'image',
//                                         'instructions' => '',
//                                         'required' => 0,
//                                         'conditional_logic' => 0,
//                                         'wrapper' => array(
//                                             'width' => '',
//                                             'class' => '',
//                                             'id' => '',
//                                         ),
//                                         'return_format' => 'array',
//                                         'preview_size' => 'medium',
//                                         'library' => '',
//                                         'min_width' => '',
//                                         'min_height' => '',
//                                         'min_size' => '',
//                                         'max_width' => '',
//                                         'max_height' => '',
//                                         'max_size' => '',
//                                         'mime_types' => '',
//                                     ),
//                                     array(
//                                         'key' => 'field_5d0baade3a0d3',
//                                         'label' => 'Title',
//                                         'name' => 'title',
//                                         'type' => 'text',
//                                         'instructions' => '',
//                                         'required' => 0,
//                                         'conditional_logic' => 0,
//                                         'wrapper' => array(
//                                             'width' => '',
//                                             'class' => '',
//                                             'id' => '',
//                                         ),
//                                         'default_value' => '',
//                                         'placeholder' => '',
//                                         'prepend' => '',
//                                         'append' => '',
//                                         'maxlength' => '',
//                                     ),
//                                 ),
//                             ),
//                             array(
//                                 'key' => 'field_5d0baae83a0d4',
//                                 'label' => 'Icon : 03',
//                                 'name' => 'icon03_grp',
//                                 'type' => 'group',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '25',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'layout' => 'block',
//                                 'sub_fields' => array(
//                                     array(
//                                         'key' => 'field_5d0baae83a0d5',
//                                         'label' => 'Icon',
//                                         'name' => 'icon',
//                                         'type' => 'image',
//                                         'instructions' => '',
//                                         'required' => 0,
//                                         'conditional_logic' => 0,
//                                         'wrapper' => array(
//                                             'width' => '',
//                                             'class' => '',
//                                             'id' => '',
//                                         ),
//                                         'return_format' => 'array',
//                                         'preview_size' => 'medium',
//                                         'library' => '',
//                                         'min_width' => '',
//                                         'min_height' => '',
//                                         'min_size' => '',
//                                         'max_width' => '',
//                                         'max_height' => '',
//                                         'max_size' => '',
//                                         'mime_types' => '',
//                                     ),
//                                     array(
//                                         'key' => 'field_5d0baae83a0d6',
//                                         'label' => 'Title',
//                                         'name' => 'title',
//                                         'type' => 'text',
//                                         'instructions' => '',
//                                         'required' => 0,
//                                         'conditional_logic' => 0,
//                                         'wrapper' => array(
//                                             'width' => '',
//                                             'class' => '',
//                                             'id' => '',
//                                         ),
//                                         'default_value' => '',
//                                         'placeholder' => '',
//                                         'prepend' => '',
//                                         'append' => '',
//                                         'maxlength' => '',
//                                     ),
//                                 ),
//                             ),
//                             array(
//                                 'key' => 'field_5d0baaf03a0d7',
//                                 'label' => 'Icon : 04',
//                                 'name' => 'icon04_grp',
//                                 'type' => 'group',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '25',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'layout' => 'block',
//                                 'sub_fields' => array(
//                                     array(
//                                         'key' => 'field_5d0baaf03a0d8',
//                                         'label' => 'Icon',
//                                         'name' => 'icon',
//                                         'type' => 'image',
//                                         'instructions' => '',
//                                         'required' => 0,
//                                         'conditional_logic' => 0,
//                                         'wrapper' => array(
//                                             'width' => '',
//                                             'class' => '',
//                                             'id' => '',
//                                         ),
//                                         'return_format' => 'array',
//                                         'preview_size' => 'medium',
//                                         'library' => 'all',
//                                         'min_width' => '',
//                                         'min_height' => '',
//                                         'min_size' => '',
//                                         'max_width' => '',
//                                         'max_height' => '',
//                                         'max_size' => '',
//                                         'mime_types' => '',
//                                     ),
//                                     array(
//                                         'key' => 'field_5d0baaf03a0d9',
//                                         'label' => 'Title',
//                                         'name' => 'title',
//                                         'type' => 'text',
//                                         'instructions' => '',
//                                         'required' => 0,
//                                         'conditional_logic' => 0,
//                                         'wrapper' => array(
//                                             'width' => '',
//                                             'class' => '',
//                                             'id' => '',
//                                         ),
//                                         'default_value' => '',
//                                         'placeholder' => '',
//                                         'prepend' => '',
//                                         'append' => '',
//                                         'maxlength' => '',
//                                     ),
//                                 ),
//                             ),
//                             array(
//                                 'key' => 'field_5d0baaf93a0da',
//                                 'label' => 'Text',
//                                 'name' => 'wysywyg',
//                                 'type' => 'wysiwyg',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'tabs' => 'all',
//                                 'toolbar' => 'full',
//                                 'media_upload' => 0,
//                                 'delay' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5d0bab0c3a0db',
//                                 'label' => 'Call to action',
//                                 'name' => 'cta',
//                                 'type' => 'link',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                             ),
//                             array(
//                                 'key' => 'field_5d42sddf7c7z',
//                                 'label' => 'Animate',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5d4fvv2f7c7b',
//                                 'label' => 'Animation',
//                                 'name' => 'animation',
//                                 'type' => 'button_group',
//                                 'instructions' => 'Content animation',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'choices' => array(
//                                     '' => 'General animation',
//                                     'sfb' => 'Slide from bottom',
//                                     'sft' => 'Slide from top',
//                                     'sfr' => 'Slide from right',
//                                     'sfl' => 'Slide from left',
//                                     'fadein' => 'Fade In',
//                                     'none' => 'No animation',
//                                 ),
//                                 'allow_null' => 0,
//                                 'default_value' => '',
//                                 'layout' => 'horizontal',
//                                 'return_format' => 'value',
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                     'layout_5bf484d7350f3' => array(
//                         'key' => 'layout_5bf484d7350f3',
//                         'name' => 'block_open_form',
//                         'label' => 'Open form',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5d4ts4g7c7z',
//                                 'label' => 'Content',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5c07dc0769a84',
//                                 'label' => 'Background : color',
//                                 'name' => 'bg_color',
//                                 'type' => 'color_picker',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5bf484e7350f4',
//                                 'label' => 'Text',
//                                 'name' => 'wysywyg',
//                                 'type' => 'wysiwyg',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'tabs' => 'all',
//                                 'toolbar' => 'full',
//                                 'media_upload' => 0,
//                                 'delay' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5bf4864fe5c0d',
//                                 'label' => 'Link : text',
//                                 'name' => 'link_text',
//                                 'type' => 'text',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'maxlength' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5bf484f6350f5',
//                                 'label' => 'Form : shortcode',
//                                 'name' => 'form_shortcode',
//                                 'type' => 'text',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'maxlength' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5bf48517350f6',
//                                 'label' => 'Custom link',
//                                 'name' => 'link',
//                                 'type' => 'link',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//
//                     'layout_5d0a8adbf43e2' => array(
//                         'key' => 'layout_5d0a8adbf43e2',
//                         'name' => 'block_instagram',
//                         'label' => 'Instagram',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5b3f9f7c4c2bx',
//                                 'label' => 'Text',
//                                 'name' => 'text',
//                                 'type' => 'wysiwyg',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'tabs' => 'all',
//                                 'toolbar' => 'full',
//                                 'media_upload' => 0,
//                                 'delay' => 0,
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                     'layout_5d362094c40ec' => array(
//                         'key' => 'layout_5d362094c40ea',
//                         'name' => 'block_iframe',
//                         'label' => 'iframe',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5db2s4g7c7z',
//                                 'label' => 'Content',
//                                 'name' => '',
//                                 'type' => 'tab',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'placement' => 'top',
//                                 'endpoint' => 0,
//                             ),
//                             array(
//                                 'key' => 'field_5d3620b0c40eb',
//                                 'label' => 'Iframe',
//                                 'name' => 'iframe_url',
//                                 'type' => 'url',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d405e9af1acf',
//                                 'label' => 'Iframe : Height',
//                                 'name' => 'iframe_height',
//                                 'type' => 'number',
//                                 'instructions' => 'height in px',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'min' => '',
//                                 'max' => '',
//                                 'step' => '',
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//
//                     //add from here
//
//                 ),
//                 'button_label' => 'Add a block',
//                 'min' => '',
//                 'max' => '',
//             ),
//
//         ),
//         'location' => array(
//             array(
//                 array(
//                     'param' => 'post_type',
//                     'operator' => '==',
//                     'value' => 'page',
//                 ),
//                 array(
//                     'param' => 'post_template',
//                     'operator' => '!=',
//                     'value' => 'news',
//                 ),
//                 array(
//                     'param' => 'post_template',
//                     'operator' => '!=',
//                     'value' => 'events',
//                 ),
//             ),
//         ),
//         'menu_order' => 3,
//         'position' => 'normal',
//         'style' => 'default',
//         'label_placement' => 'top',
//         'instruction_placement' => 'label',
//         'hide_on_screen' => array(
//             0 => 'the_content',
//         ),
//         'active' => 1,
//         'description' => '',
//     ));
// endif;
