<?php
if( function_exists('acf_add_local_field_group') ):
acf_add_local_field_group(array(
    'key' => 'group_5bf476dcd74ed',
    'title' => 'Customize',
    'fields' => array(
        array(
            'key' => 'field_5bf597307c5d6',
            'label' => 'Header',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5c07dfba90bf5',
            'label' => 'Menu',
            'name' => 'menu_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                //TOP BAR
                array(
                    'key' => 'field_5bf72e9b0a4fa',
                    'label' => 'Background color',
                    'name' => 'top_bar_color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72f160ac58',
                    'label' => 'Opacity',
                    'name' => 'top_bar_opacity',
                    'type' => 'range',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '45',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => 0,
                    'max' => 1,
                    'step' => '0.1',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_5c07dfe890bf6',
                    'label' => 'Links : color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c084d57a0d72',
                    'label' => 'Links : color hover',
                    'name' => 'color_hover',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
        			'key' => 'field_5e2fxx0dc83ae7',
        			'label' => 'Links : animation',
        			'name' => 'links_animation',
        			'type' => 'button_group',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'choices' => array(
        				'grow-left' => 'Left to right',
        				'grow-mid' => 'From middle',
                        'grow-right' => 'Right to left',
        			),
        			'allow_null' => 0,
        			'default_value' => '',
        			'layout' => 'horizontal',
        			'return_format' => 'value',
        		),
                array(
                    'key' => 'field_5bf5a75f8c0d6',
                    'label' => 'Logo',
                    'name' => 'logo',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_5c8112650ecb1',
                    'label' => 'Logo : width (px)',
                    'name' => 'logo_width',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),



        //HERO
        array(
            'key' => 'field_5d38b0748db02',
            'label' => 'Hero',
            'name' => 'hero',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5d38b0a68db03',
                    'label' => 'Overlay: color',
                    'name' => 'overlay_color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5d38b1138db04',
                    'label' => 'Overlay: opacity',
                    'name' => 'overlay_opacity',
                    'type' => 'range',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => 0,
                    'max' => 1,
                    'step' => '0.1',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_5bfdf2xeffa283',
                    'label' => 'Slider Height (vh)',
                    'name' => 'slider_height',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '50',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '100',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bfdf2xefsdfa283',
                    'label' => 'Normal (vh)',
                    'name' => 'normal_height',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '50',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '100',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5d38b1a8f79d6',
                    'label' => 'Slider Arrow : left',
                    'name' => 'arrow_left',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_5d38b1d1f79d7',
                    'label' => 'Slider Arrow : right',
                    'name' => 'arrow_right',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_5d38b1fef79d8',
                    'label' => 'Slider Speed',
                    'name' => 'slider_speed',
                    'type' => 'number',
                    'instructions' => 'Seconds',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5bf597517c5d7',
            'label' => 'Footer',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),



        array(
            'key' => 'field_5c085096003f8',
            'label' => 'Background : image',
            'name' => 'footer_bg_image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_5c0850b3003f9',
            'label' => 'Background : color',
            'name' => 'footer_bg_color',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
        array(
            'key' => 'field_5c41da8f8681d',
            'label' => 'Title : color',
            'name' => 'footer_text_color',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),



        array(
            'key' => 'field_5bf59add0494f',
            'label' => 'Newsletter[EN]',
            'name' => 'footer_newsletter_en',
            'type' => 'text',
            'instructions' => 'Add form shortcode',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5bf59af304950',
            'label' => 'Newsletter[FR]',
            'name' => 'footer_newsletter_fr',
            'type' => 'text',
            'instructions' => 'Add form shortcode',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),

        array(
            'key' => 'field_5bf598f07189x',
            'label' => 'Call to action[FR]',
            'name' => 'footer_cta_fr',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
        array(
            'key' => 'field_5bf598f07189p',
            'label' => 'Call to action[EN]',
            'name' => 'footer_cta_en',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
        array(
            'key' => 'field_5c41d86c55564',
            'label' => 'Bottom Link Background Color : Left and Right',
            'name' => 'footer_bottom_link_bg_color_lr',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
        array(
            'key' => 'field_5c41d9e9fb057',
            'label' => 'Bottom Link Background Color : Middle',
            'name' => 'footer_bottom_link_bg_color_mid',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
        array(
            'key' => 'field_5bf59769eb75b',
            'label' => 'Copyrights[EN]',
            'name' => 'copyrights_en',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5bf59801eb75c',
            'label' => 'Copyrights[FR]',
            'name' => 'copyrights_fr',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5bf876dd7d582',
            'label' => 'Disable footer',
            'name' => 'footer_disable',
            'type' => 'relationship',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'page',
            ),
            'taxonomy' => '',
            'filters' => array(
                0 => 'post_type',
            ),
            'elements' => '',
            'min' => '',
            'max' => '',
            'return_format' => 'object',
        ),
        array(
            'key' => 'field_5bf476f1d7db6',
            'label' => 'Typography',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5bf47a6294bcb',
            'label' => 'Font family',
            'name' => 'font_family',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'Poppins, sans-serif' => 'Poppins',
                'Roboto, sans-serif' => 'Roboto',
                'Lato, sans-serif' => 'Lato',
                'Montserrat, sans-serif' => 'Montserrat',
                'PT Sans, sans-serif' => 'PT Sans',
                'Open Sans, sans-serif' => 'Open Sans',
                'Merriweather, serif' => 'Merriweather',
            ),
            'default_value' => array(
                0 => 'Poppins',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'array',
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_5d42xdsfsdf3e8d43',
            'label' => 'Preview',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'wrapper' => array(
                'width' => '75',
                'class' => 'typo-preview',
                'id' => '',
            ),
            'message' => '<p style="font-size:16px">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ut lacus purus. Pellentesque ultricies imperdiet elit vel suscipit. Nulla facilisi. Donec augue enim, eleifend et massa non, aliquet lobortis sem. Aliquam eu mi ipsum.<p>',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        array(
            'key' => 'field_5bf47709d7db7',
            'label' => 'H1',
            'name' => 'h1_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5bf47756d7db8',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf7265a6680d',
                    'label' => 'Font-size : phone',
                    'name' => 'fz_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bfdf2xe2ga283',
                    'label' => 'Line Height : phone',
                    'name' => 'lh_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf726796680e',
                    'label' => 'Font-size : desktop',
                    'name' => 'fz_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),

                array(
                    'key' => 'field_5bf72cde2ga283',
                    'label' => 'Line Height : desktop',
                    'name' => 'lh_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),

            ),
        ),
        array(
            'key' => 'field_5bf72bc7ca279',
            'label' => 'H2',
            'name' => 'h2_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5bf72bc7ca27a',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72bc7ca27b',
                    'label' => 'Font-size : phone',
                    'name' => 'fz_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72sdfde2ga283',
                    'label' => 'Line Height : phone',
                    'name' => 'lh_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72bc7ca27c',
                    'label' => 'Font-size : desktop',
                    'name' => 'fz_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72cde2gfff283',
                    'label' => 'Line Height : desktop',
                    'name' => 'lh_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5bf72bd3ca27d',
            'label' => 'H3',
            'name' => 'h3_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5bf72bd3ca27e',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72bd3ca27f',
                    'label' => 'Font-size : phone',
                    'name' => 'fz_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5sxf72cde2ga283',
                    'label' => 'Line Height : phone',
                    'name' => 'lh_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72bd4ca280',
                    'label' => 'Font-size : desktop',
                    'name' => 'fz_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72dsfsdde2ga283',
                    'label' => 'Line Height : desktop',
                    'name' => 'lh_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5bf72be2ca281',
            'label' => 'Paragraph',
            'name' => 'paragraph_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5bf72be2ca282',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72be2ca283',
                    'label' => 'Font-size : phone',
                    'name' => 'fz_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72be2ga283',
                    'label' => 'Line Height : phone',
                    'name' => 'lh_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72be2ca284',
                    'label' => 'Font-size : desktop',
                    'name' => 'fz_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72xe2ga283',
                    'label' => 'Line Height : desktop',
                    'name' => 'lh_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72dsfe2ga283',
                    'label' => 'Letter spacing : phone',
                    'name' => 'lp_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf7sdfdsfe2ga283',
                    'label' => 'Letter spacing : desktop',
                    'name' => 'lp_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5bf72bfaca285',
            'label' => 'Link',
            'name' => 'link_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5bf72bfaca286',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72c09ca289',
                    'label' => 'Color : hover',
                    'name' => 'color_hover',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72bfaca287',
                    'label' => 'Font-size : phone',
                    'name' => 'fz_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72bfaca288',
                    'label' => 'Font-size : desktop',
                    'name' => 'fz_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5bf72cf80b478',
            'label' => 'Small elements',
            'name' => 'span_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5bf72cf80b479',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72cf80b47a',
                    'label' => 'Font-size : phone',
                    'name' => 'fz_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72cf80b47b',
                    'label' => 'Font-size : desktop',
                    'name' => 'fz_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5c07d6e816118',
            'label' => 'Elements',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),

        array(
            'key' => 'field_5c07d70016119',
            'label' => 'Buttons',
            'name' => 'button_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5d42x113e8d43',
                    'label' => 'Preview',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'button-preview',
                        'id' => '',
                    ),
                    'message' => '<a href="#" class="cta default">Button</a> <a href="#" class="cta hover">Button : hover</a>',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
                array(
                    'key' => 'field_5c07d71c1611a',
                    'label' => 'Text : Color',
                    'name' => 'text_color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c07d7561611b',
                    'label' => 'Text : color transition',
                    'name' => 'text_color_transition',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c07d7781611c',
                    'label' => 'Background : color',
                    'name' => 'bg_color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c07d7a61611d',
                    'label' => 'Background : color transition',
                    'name' => 'bg_color_transition',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c07d7c31611f',
                    'label' => 'Border : color',
                    'name' => 'border_color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c07d7d016120',
                    'label' => 'Border : color transition',
                    'name' => 'border_color_transition',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
            ),

        ),
        array(
            'key' => 'field_5c07d6e816114',
            'label' => 'Form',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5c07dfca90bf5',
            'label' => 'Page Contact',
            'name' => 'contact_form_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
              array(
                  'key' => 'field_5bf72cf80b47v',
                  'label' => 'Title : Color',
                  'name' => 'form_title_color',
                  'type' => 'color_picker',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                      'width' => '25',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
              ),
              array(
                  'key' => 'field_5bf72cf80b471',
                  'label' => 'Label : Color',
                  'name' => 'form_label_color',
                  'type' => 'color_picker',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                      'width' => '25',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
              ),
              array(
                  'key' => 'field_5bf72cf80b4745',
                  'label' => 'Input border : Color',
                  'name' => 'form_border_color',
                  'type' => 'color_picker',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                      'width' => '25',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
              ),
              array(
                      'key' => 'field_5c07d71c1v11a',
                      'label' => 'Submit button : Text color',
                      'name' => 'text_color',
                      'type' => 'color_picker',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                          'width' => '50',
                          'class' => '',
                          'id' => '',
                      ),
                      'default_value' => '',
                  ),
                  array(
                      'key' => 'field_5c07d75x1611b',
                      'label' => 'Submit button : Text color transition',
                      'name' => 'text_color_transition',
                      'type' => 'color_picker',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                          'width' => '50',
                          'class' => '',
                          'id' => '',
                      ),
                      'default_value' => '',
                  ),
                  array(
                      'key' => 'field_5c07d7781v11c',
                      'label' => 'Submit button : Background color',
                      'name' => 'bg_color',
                      'type' => 'color_picker',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                          'width' => '50',
                          'class' => '',
                          'id' => '',
                      ),
                      'default_value' => '',
                  ),
                  array(
                      'key' => 'field_5c0cd7a61611d',
                      'label' => 'Submit button : Background color transition',
                      'name' => 'bg_color_transition',
                      'type' => 'color_picker',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                          'width' => '50',
                          'class' => '',
                          'id' => '',
                      ),
                      'default_value' => '',
                  ),

            ),
        ),
        array(
            'key' => 'field_5c07dfcff90bc5',
            'label' => 'Modal',
            'name' => 'modal_form_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
              array(
                  'key' => 'field_5bf72cfr80b47v',
                  'label' => 'Background : Color',
                  'name' => 'background_color',
                  'type' => 'color_picker',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                      'width' => '25',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
              ),
              array(
                  'key' => 'field_5bf72cf80b47vr80b47v',
                  'label' => 'Placeholder : Color',
                  'name' => 'placeholder_color',
                  'type' => 'color_picker',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                      'width' => '25',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
              ),
              array(
                  'key' => 'field_5bf72cf8xb471',
                  'label' => 'Label : Color',
                  'name' => 'form_label_color',
                  'type' => 'color_picker',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                      'width' => '25',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
              ),
              array(
                  'key' => 'field_5bf72cf80bb745',
                  'label' => 'Input border : Color',
                  'name' => 'form_border_color',
                  'type' => 'color_picker',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                      'width' => '25',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
              ),

              array(
                  'key' => 'field_5c07d7cc1v11a',
                  'label' => 'Submit button : Text color',
                  'name' => 'text_color',
                  'type' => 'color_picker',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
                  ),
              array(
                  'key' => 'field_5c07ddf5x1611b',
                  'label' => 'Submit button : Text color transition',
                  'name' => 'text_color_transition',
                  'type' => 'color_picker',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
              ),
              array(
                  'key' => 'field_5c07ee781v11c',
                  'label' => 'Submit button : Background color',
                  'name' => 'bg_color',
                  'type' => 'color_picker',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
              ),
              array(
                  'key' => 'field_5c0cdff61611d',
                  'label' => 'Submit button : Background color transition',
                  'name' => 'bg_color_transition',
                  'type' => 'color_picker',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
              ),

            ),
        ),
        array(
            'key' => 'field_5d42007f4d227',
            'label' => 'Animation',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5d42df920be6b',
            'label' => 'Content animation for all the site',
            'name' => 'content_animation',
            'type' => 'group',
            'instructions' => 'Set the default animation for all content. Can be overwrite in the block option',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5d42dff80be6c',
                    'label' => 'Animation',
                    'name' => 'animation',
                    'type' => 'button_group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'none' => 'None',
                        'sfb' => 'Slide from bottom',
                        'sft' => 'Slide from top',
                        'sfr' => 'Slide from right',
                        'sfl' => 'Slide from left',
                        'fadein' => 'Fade In',
                    ),
                    'allow_null' => 0,
                    'default_value' => '',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_5d42e113e8d43',
                    'label' => 'Slide from bottom',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5d42dff80be6c',
                                'operator' => '==',
                                'value' => 'sfb',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'do-animation sfb',
                        'id' => '',
                    ),
                    'message' => '<h1 style="text-align: center">Slide from bottom</h1>',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
                array(
                    'key' => 'field_5d42e113e8d4x',
                    'label' => 'Slide from top',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5d42dff80be6c',
                                'operator' => '==',
                                'value' => 'sft',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'do-animation sft',
                        'id' => '',
                    ),
                    'message' => '<h1 style="text-align: center">Slide from top</h1>',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
                array(
                    'key' => 'field_5d42e113e8d4q',
                    'label' => 'Slide from right',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5d42dff80be6c',
                                'operator' => '==',
                                'value' => 'sfr',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'do-animation sfr',
                        'id' => '',
                    ),
                    'message' => '<h1 style="text-align: center">Slide from right</h1>',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
                array(
                    'key' => 'field_5d42e113e8d4c',
                    'label' => 'Slide from left',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5d42dff80be6c',
                                'operator' => '==',
                                'value' => 'sfl',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'do-animation sfl',
                        'id' => '',
                    ),
                    'message' => '<h1 style="text-align:center">Slide from left</h1>',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
                array(
                    'key' => 'field_5d42e113e8d4f',
                    'label' => 'Fade In',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5d42dff80be6c',
                                'operator' => '==',
                                'value' => 'fadein',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'do-animation fadein',
                        'id' => '',
                    ),
                    'message' => '<h1 style="text-align:center">Fade In</h1>',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
            ),

        ),
        array(
            'key' => 'field_5d4200ae5ca45',
            'label' => 'Animation properties',
            'name' => 'animation_props',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5d4200ed5ca47',
                    'label' => 'Easing',
                    'name' => 'easing',
                    'type' => 'select',
                    'instructions' => 'https://easings.net/',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'linear' => 'Linear',
                        'ease' => 'Ease',
                        'ease-in' => 'Ease-in',
                        'ease-out' => 'Ease-out',
                        // 'custom' => 'Custom',
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5d4200cf5ca46',
                    'label' => 'Duration',
                    'name' => 'duration',
                    'type' => 'number',
                    'instructions' => 'Second(s)',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '.1',
                ),
                array(
                    'key' => 'field_5d4201ad5ca49',
                    'label' => 'Delay',
                    'name' => 'delay',
                    'type' => 'number',
                    'instructions' => 'Second(s)',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '0.1',
                ),
            ),
        ),


    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'customize',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

endif;
