<?php

acf_add_local_field_group(array(
    'key' => 'group_5bf476dcd74ed',
    'title' => 'Customize',
    'fields' => array(
        array(
            'key' => 'field_5bf597307c5d6',
            'label' => 'Header',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5c07dfba90bf5',
            'label' => 'Menu',
            'name' => 'menu_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                //TOP BAR
                array(
                    'key' => 'field_5bf72e9b0a4fa',
                    'label' => 'Top bar : background color',
                    'name' => 'top_bar_color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72f160ac58',
                    'label' => 'Top bar : opacity',
                    'name' => 'top_bar_opacity',
                    'type' => 'range',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '45',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => 0,
                    'max' => 1,
                    'step' => '0.1',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_5c07dfe890bf6',
                    'label' => 'Links : color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c084d57a0d72',
                    'label' => 'Links : color hover',
                    'name' => 'color_hover',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c084bee57236',
                    'label' => 'Links : color on sticky menu',
                    'name' => 'color_sticky',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c084d65a0d73',
                    'label' => 'Links : color on sticky hover',
                    'name' => 'color_sticky_hover',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf5a75f8c0d6',
                    'label' => 'Logo',
                    'name' => 'logo',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_5c8112650ecb1',
                    'label' => 'Logo : width (px)',
                    'name' => 'logo_width',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),



        //HERO
        array(
            'key' => 'field_5d38b0748db02',
            'label' => 'Hero',
            'name' => 'hero',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5d38b0a68db03',
                    'label' => 'Overlay: color',
                    'name' => 'overlay_color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5d38b1138db04',
                    'label' => 'Overlay: opacity',
                    'name' => 'overlay_opacity',
                    'type' => 'range',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => 0,
                    'max' => 1,
                    'step' => '0.1',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_5d38b1a8f79d6',
                    'label' => 'Slider Arrow : left',
                    'name' => 'arrow_left',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_5d38b1d1f79d7',
                    'label' => 'Slider Arrow : right',
                    'name' => 'arrow_right',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_5d38b1fef79d8',
                    'label' => 'Slider Speed',
                    'name' => 'slider_speed',
                    'type' => 'number',
                    'instructions' => 'Seconds',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5bf597517c5d7',
            'label' => 'Footer',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5bf876dd7d582',
            'label' => 'Disable footer',
            'name' => 'footer_disable',
            'type' => 'relationship',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'page',
            ),
            'taxonomy' => '',
            'filters' => array(
                0 => 'post_type',
            ),
            'elements' => '',
            'min' => '',
            'max' => '',
            'return_format' => 'object',
        ),
//        array(
//            'key' => 'field_5bf59812eb75d',
//            'label' => 'Logo',
//            'name' => 'footer_logo',
//            'type' => 'image',
//            'instructions' => '',
//            'required' => 0,
//            'conditional_logic' => 0,
//            'wrapper' => array(
//                'width' => '50',
//                'class' => '',
//                'id' => '',
//            ),
//            'return_format' => 'array',
//            'preview_size' => 'thumbnail',
//            'library' => 'all',
//            'min_width' => '',
//            'min_height' => '',
//            'min_size' => '',
//            'max_width' => '',
//            'max_height' => '',
//            'max_size' => '',
//            'mime_types' => '',
//        ),

        array(
            'key' => 'field_5c085096003f8',
            'label' => 'Background : image',
            'name' => 'footer_bg_image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_5c0850b3003f9',
            'label' => 'Background : color',
            'name' => 'footer_bg_color',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
        array(
            'key' => 'field_5c41da8f8681d',
            'label' => 'Text : color',
            'name' => 'footer_text_color',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),


//        array(
//            'key' => 'field_5bf5990d718ak',
//            'label' => 'Google map : Key',
//            'name' => 'google_map_key',
//            'type' => 'text',
//            'instructions' => 'Add a key to enable the map',
//            'required' => 0,
//            'conditional_logic' => 0,
//            'wrapper' => array(
//                'width' => '',
//                'class' => '',
//                'id' => '',
//            ),
//            'default_value' => '',
//            'placeholder' => '',
//            'prepend' => '',
//            'append' => '',
//            'maxlength' => '',
//        ),
//        array(
//            'key' => 'field_5bf5990d718a0',
//            'label' => 'Google map : Latitude',
//            'name' => 'footer_latitude',
//            'type' => 'text',
//            'instructions' => '',
//            'required' => 0,
//            'conditional_logic' => 0,
//            'wrapper' => array(
//                'width' => '50',
//                'class' => '',
//                'id' => '',
//            ),
//            'default_value' => '',
//            'placeholder' => '',
//            'prepend' => '',
//            'append' => '',
//            'maxlength' => '',
//        ),
//        array(
//            'key' => 'field_5bf598f07189f',
//            'label' => 'Google map : Longitude',
//            'name' => 'footer_longitude',
//            'type' => 'text',
//            'instructions' => '',
//            'required' => 0,
//            'conditional_logic' => 0,
//            'wrapper' => array(
//                'width' => '50',
//                'class' => '',
//                'id' => '',
//            ),
//            'default_value' => '',
//            'placeholder' => '',
//            'prepend' => '',
//            'append' => '',
//            'maxlength' => '',
//        ),
//        array(
//            'key' => 'field_5bf59d48488c0',
//            'label' => 'Google map : Url',
//            'name' => 'footer_google_map_url',
//            'type' => 'text',
//            'instructions' => 'Add a link on the map',
//            'required' => 0,
//            'conditional_logic' => 0,
//            'wrapper' => array(
//                'width' => '',
//                'class' => '',
//                'id' => '',
//            ),
//            'default_value' => '',
//            'placeholder' => '',
//            'prepend' => '',
//            'append' => '',
//            'maxlength' => '',
//        ),
//        array(
//            'key' => 'field_5bf59d48488cf',
//            'label' => 'Google map : Style',
//            'name' => 'footer_google_map_style',
//            'type' => 'textarea',
//            'instructions' => 'Copy the code here source(https://snazzymaps.com/) ',
//            'required' => 0,
//            'conditional_logic' => 0,
//            'wrapper' => array(
//                'width' => '',
//                'class' => '',
//                'id' => '',
//            ),
//            'default_value' => '',
//            'placeholder' => '',
//            'prepend' => '',
//            'append' => '',
//            'maxlength' => '',
//        ),
        array(
            'key' => 'field_5bf59add0494f',
            'label' => 'Newsletter[EN]',
            'name' => 'footer_newsletter_en',
            'type' => 'text',
            'instructions' => 'Add form shortcode',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5bf59af304950',
            'label' => 'Newsletter[FR]',
            'name' => 'footer_newsletter_fr',
            'type' => 'text',
            'instructions' => 'Add form shortcode',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),

        array(
            'key' => 'field_5bf598f07189x',
            'label' => 'Call to action[FR]',
            'name' => 'footer_cta_fr',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
        array(
            'key' => 'field_5bf598f07189p',
            'label' => 'Call to action[EN]',
            'name' => 'footer_cta_en',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
        array(
            'key' => 'field_5c41d86c55564',
            'label' => 'Bottom Link Background Color : Left and Right',
            'name' => 'footer_bottom_link_bg_color_lr',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
        array(
            'key' => 'field_5c41d9e9fb057',
            'label' => 'Bottom Link Background Color : Middle',
            'name' => 'footer_bottom_link_bg_color_mid',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
        array(
            'key' => 'field_5bf59769eb75b',
            'label' => 'Copyrights[EN]',
            'name' => 'copyrights_en',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5bf59801eb75c',
            'label' => 'Copyrights[FR]',
            'name' => 'copyrights_fr',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5bf476f1d7db6',
            'label' => 'Typography',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5bf47a6294bcb',
            'label' => 'Font family',
            'name' => 'font_family',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'Poppins' => 'Poppins',
                'Roboto' => 'Roboto',
                'Lato' => 'Lato',
                'Montserrat' => 'Montserrat',
            ),
            'default_value' => array(
                0 => 'Poppins',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'array',
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_5bf47709d7db7',
            'label' => 'H1',
            'name' => 'h1_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5bf47756d7db8',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf7265a6680d',
                    'label' => 'Font-size : phone',
                    'name' => 'fz_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf726796680e',
                    'label' => 'Font-size : desktop',
                    'name' => 'fz_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5bf72bc7ca279',
            'label' => 'H2',
            'name' => 'h2_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5bf72bc7ca27a',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72bc7ca27b',
                    'label' => 'Font-size : phone',
                    'name' => 'fz_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72bc7ca27c',
                    'label' => 'Font-size : desktop',
                    'name' => 'fz_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5bf72bd3ca27d',
            'label' => 'H3',
            'name' => 'h3_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5bf72bd3ca27e',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72bd3ca27f',
                    'label' => 'Font-size : phone',
                    'name' => 'fz_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72bd4ca280',
                    'label' => 'Font-size : desktop',
                    'name' => 'fz_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5bf72be2ca281',
            'label' => 'Paragraph',
            'name' => 'paragraph_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5bf72be2ca282',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72be2ca283',
                    'label' => 'Font-size : phone',
                    'name' => 'fz_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72be2ca284',
                    'label' => 'Font-size : desktop',
                    'name' => 'fz_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5bf72bfaca285',
            'label' => 'Link',
            'name' => 'link_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5bf72bfaca286',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72c09ca289',
                    'label' => 'Color : hover',
                    'name' => 'color_hover',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72bfaca287',
                    'label' => 'Font-size : phone',
                    'name' => 'fz_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72bfaca288',
                    'label' => 'Font-size : desktop',
                    'name' => 'fz_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5bf72cf80b478',
            'label' => 'Span',
            'name' => 'span_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5bf72cf80b479',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5bf72cf80b47a',
                    'label' => 'Font-size : phone',
                    'name' => 'fz_phone',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bf72cf80b47b',
                    'label' => 'Font-size : desktop',
                    'name' => 'fz_desktop',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5c07d6e816118',
            'label' => 'Elements',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),

        array(
            'key' => 'field_5c07d70016119',
            'label' => 'Buttons',
            'name' => 'button_grp',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5c07d71c1611a',
                    'label' => 'Text : color',
                    'name' => 'text_color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c07d7561611b',
                    'label' => 'Text : color transition',
                    'name' => 'text_color_transition',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c07d7781611c',
                    'label' => 'Background : color',
                    'name' => 'bg_color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c07d7a61611d',
                    'label' => 'Background : color transition',
                    'name' => 'bg_color_transition',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c07d7c31611f',
                    'label' => 'Border : color',
                    'name' => 'border_color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_5c07d7d016120',
                    'label' => 'Border : color transition',
                    'name' => 'border_color_transition',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
            ),

        ),
        array(
            'key' => 'field_5c07d6e816114',
            'label' => 'Form',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5bf72cf80b47v',
            'label' => 'Title : Color',
            'name' => 'form_title_color',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
        array(
            'key' => 'field_5bf72cf80b471',
            'label' => 'Label : Color',
            'name' => 'form_label_color',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
        array(
            'key' => 'field_5bf72cf80b4745',
            'label' => 'Input border : Color',
            'name' => 'form_border_color',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
        array(
            'key' => 'field_5d42007f4d227',
            'label' => 'Animation',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5d4200ae5ca45',
            'label' => 'General',
            'name' => 'animation_all',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5d4200ed5ca47',
                    'label' => 'Effect',
                    'name' => 'effect',
                    'type' => 'select',
                    'instructions' => 'To visualize : https://easings.net/',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'none' => 'None',
                        'custom' => 'Custom',
                        'ease' => 'Ease',
                        'ease-in' => 'Ease-in',
                        'ease-out' => 'Ease-out',
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5d4201825ca48',
                    'label' => 'Effect custom',
                    'name' => 'effect_custom',
                    'type' => 'text',
                    'instructions' => 'https://easings.net/',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5d4200ed5ca47',
                                'operator' => '==',
                                'value' => 'custom',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'cubic-bezier(0.55, 0.085, 0.68, 0.53)',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5d4200cf5ca46',
                    'label' => 'Duration',
                    'name' => 'duration',
                    'type' => 'number',
                    'instructions' => 'Second(s)',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '.1',
                ),
                array(
                    'key' => 'field_5d4201ad5ca49',
                    'label' => 'Delay',
                    'name' => 'delay',
                    'type' => 'number',
                    'instructions' => 'Second(s)',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '0.1',
                ),
            ),
        ),

        array(
            'key' => 'field_5d42df920be6b',
            'label' => 'Content animation',
            'name' => 'content_animation',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_5d42dff80be6c',
                    'label' => 'Animation',
                    'name' => 'animation',
                    'type' => 'button_group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'sfb' => 'Slide from bottom',
                        'sft' => 'Slide from top',
                        'sfr' => 'Slide from right',
                        'sfl' => 'Slide from left',
                        'fadein' => 'Fade In',
                    ),
                    'allow_null' => 0,
                    'default_value' => '',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_5d42e113e8d43',
                    'label' => 'Slide from bottom',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5d42dff80be6c',
                                'operator' => '==',
                                'value' => 'sfb',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'do-animation sfb',
                        'id' => '',
                    ),
                    'message' => '<h1 style="text-align: center">Slide from bottom</h1>',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
                array(
                    'key' => 'field_5d42e113e8d4x',
                    'label' => 'Slide from top',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5d42dff80be6c',
                                'operator' => '==',
                                'value' => 'sft',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'do-animation sft',
                        'id' => '',
                    ),
                    'message' => '<h1 style="text-align: center">Slide from top</h1>',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
                array(
                    'key' => 'field_5d42e113e8d4q',
                    'label' => 'Slide from right',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5d42dff80be6c',
                                'operator' => '==',
                                'value' => 'sfr',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'do-animation sfr',
                        'id' => '',
                    ),
                    'message' => '<h1 style="text-align: center">Slide from right</h1>',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
                array(
                    'key' => 'field_5d42e113e8d4c',
                    'label' => 'Slide from left',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5d42dff80be6c',
                                'operator' => '==',
                                'value' => 'sfl',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'do-animation sfl',
                        'id' => '',
                    ),
                    'message' => '<h1 style="text-align:center">Slide from left</h1>',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
                array(
                    'key' => 'field_5d42e113e8d4f',
                    'label' => 'Fade In',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5d42dff80be6c',
                                'operator' => '==',
                                'value' => 'fadein',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'do-animation fadein',
                        'id' => '',
                    ),
                    'message' => '<h1 style="text-align:center">Fade In</h1>',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
            ),

        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'customize',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));