<?php

if( function_exists('acf_add_local_field_group') ):
acf_add_local_field_group(array(
    'key' => 'group_5bf476dcd74ex',
    'title' => 'Google map',
    'fields' => array(

        array(
            'key' => 'field_5bf5990d718ak',
            'label' => 'Google map : Key',
            'name' => 'google_map_key',
            'type' => 'text',
            'instructions' => 'Add a key to enable the map',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5bf5990d718a0',
            'label' => 'Google map : Latitude',
            'name' => 'google_map_latitude',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        
        array(
            'key' => 'field_5bf598f07189f',
            'label' => 'Google map : Longitude',
            'name' => 'google_map_longitude',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5bf59d48488c0',
            'label' => 'Google map : Url',
            'name' => 'google_map_url',
            'type' => 'text',
            'instructions' => 'Add a link on the map',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5bf59d48488cf',
            'label' => 'Google map : Style',
            'name' => 'google_map_style',
            'type' => 'textarea',
            'instructions' => 'Copy the code here source(https://snazzymaps.com/) ',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'google-map',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
endif;
