<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5bf5d4239dc46',
        'title' => 'Page contact',
        'fields' => array(
            array(
                'key' => 'field_5bf6a9461c312',
                'label' => 'Title',
                'name' => 'contact_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5bf2b45d3b8f12',
                'label' => 'Text',
                'name' => 'contact_wysiwyg',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
                'delay' => 0,
            ),
            array(
                'key' => 'field_5bf6a9291c311',
                'label' => 'Form : shortcode',
                'name' => 'contact_form_shortcode',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_template',
                    'operator' => '==',
                    'value' => 'contact',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));



    acf_add_local_field_group(array(
        'key' => 'group_5bf2b7e989d5a',
        'title' => 'Header',
        'fields' => array(
            array(
                'key' => 'field_5bf4298bd6fde',
                'label' => 'Use a slider?',
                'name' => 'use_a_slider',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
//            array(
//                'key' => 'field_5bf2b81712515',
//                'label' => 'Image : phone',
//                'name' => 'header_image_phone',
//                'type' => 'image',
//                'instructions' => 'No slider on phone',
//                'required' => 0,
//                'conditional_logic' => array(
//                    array(
//                        array(
//                            'field' => 'field_5bf4298bd6fde',
//                            'operator' => '==',
//                            'value' => '1',
//                        ),
//                    ),
//                ),
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'return_format' => 'array',
//                'preview_size' => 'thumbnail',
//                'library' => 'all',
//                'min_width' => '',
//                'min_height' => '',
//                'min_size' => '',
//                'max_width' => '',
//                'max_height' => '',
//                'max_size' => '',
//                'mime_types' => '',
//            ),
            array(
                'key' => 'field_5bf2b86312516',
                'label' => 'Images : Slider',
                'name' => 'header_slider_image',
                'type' => 'gallery',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5bf4298bd6fde',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'min' => '',
                'max' => '',
                'insert' => 'append',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5bf2b89012517',
                'label' => 'Logo',
                'name' => 'header_logo',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5bf4298bd6fde',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5bf42a58d6fdf',
                'label' => 'Image',
                'name' => 'header_image_background',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5bf4298bd6fde',
                            'operator' => '!=',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5bf42afed6fe0',
                'label' => 'Title',
                'name' => 'header_image_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5bf4298bd6fde',
                            'operator' => '!=',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => 1,
        'description' => '',
    ));

//    acf_add_local_field_group(array(
//        'key' => 'group_5bf2b42e0d67d',
//        'title' => 'Blocks',
//        'fields' => array(
//            array(
//                'key' => 'field_5bf2b4d429f3a',
//                'label' => 'Blocks',
//                'name' => 'blocks',
//                'type' => 'flexible_content',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'layouts' => array(
//                    '5bf2b4dfc6e40' => array(
//                        'key' => '5bf2b4dfc6e40',
//                        'name' => 'block_discover',
//                        'label' => 'Discover',
//                        'display' => 'block',
//                        'sub_fields' => array(
//                            array(
//                                'key' => 'field_5c07db8d8825b',
//                                'label' => 'Background : color',
//                                'name' => 'bg_color',
//                                'type' => 'color_picker',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                            ),
//                            array(
//                                'key' => 'field_5bf2b4ef29f3b',
//                                'label' => 'Logo',
//                                'name' => 'logo',
//                                'type' => 'image',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '50',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'return_format' => 'array',
//                                'preview_size' => 'thumbnail',
//                                'library' => 'all',
//                                'min_width' => '',
//                                'min_height' => '',
//                                'min_size' => '',
//                                'max_width' => '',
//                                'max_height' => '',
//                                'max_size' => '',
//                                'mime_types' => '',
//                            ),
//                            array(
//                                'key' => 'field_5c8112650ecb1',
//                                'label' => 'Logo : width (px)',
//                                'name' => 'logo_width',
//                                'type' => 'number',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '50',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                                'min' => '',
//                                'max' => '',
//                                'step' => '',
//                            ),
//                            array(
//                                'key' => 'field_5bf2b45d3b8fc',
//                                'label' => 'Text',
//                                'name' => 'wysywyg',
//                                'type' => 'wysiwyg',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'tabs' => 'all',
//                                'toolbar' => 'full',
//                                'media_upload' => 0,
//                                'delay' => 0,
//                            ),
//                            array(
//                                'key' => 'field_5bf2b47a4708c',
//                                'label' => 'Discover Link : left',
//                                'name' => 'link_left',
//                                'type' => 'link',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '50',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'return_format' => 'array',
//                            ),
//                            array(
//                                'key' => 'field_5bf2b4a64708d',
//                                'label' => 'Discover Link : right',
//                                'name' => 'link_right',
//                                'type' => 'link',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '50',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'return_format' => 'array',
//                            ),
//                        ),
//                        'min' => '',
//                        'max' => '',
//                    ),
//                    '5bf419776d222' => array(
//                        'key' => '5bf419776d222',
//                        'name' => 'block_text',
//                        'label' => 'Text',
//                        'display' => 'block',
//                        'sub_fields' => array(
//                            array(
//                                'key' => 'field_5c07dbbd69a82',
//                                'label' => 'Background : color',
//                                'name' => 'bg_color',
//                                'type' => 'color_picker',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                            ),
//                            array(
//                                'key' => 'field_5bf419b46d223',
//                                'label' => 'Text',
//                                'name' => 'wysywyg',
//                                'type' => 'wysiwyg',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'tabs' => 'all',
//                                'toolbar' => 'full',
//                                'media_upload' => 0,
//                                'delay' => 0,
//                            ),
//                        ),
//                        'min' => '',
//                        'max' => '',
//                    ),
//                    '5bf2bcdb4fd35' => array(
//                        'key' => '5bf2bcdb4fd35',
//                        'name' => 'block_background_title',
//                        'label' => 'Background & Title',
//                        'display' => 'block',
//                        'sub_fields' => array(
//                            array(
//                                'key' => 'field_5bf2bcea4fd36',
//                                'label' => 'Image : background',
//                                'name' => 'background',
//                                'type' => 'image',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'return_format' => 'array',
//                                'preview_size' => 'thumbnail',
//                                'library' => 'all',
//                                'min_width' => '',
//                                'min_height' => '',
//                                'min_size' => '',
//                                'max_width' => '',
//                                'max_height' => '',
//                                'max_size' => '',
//                                'mime_types' => '',
//                            ),
//                            array(
//                                'key' => 'field_5bf2bd044fd37',
//                                'label' => 'Title',
//                                'name' => 'title',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                                'maxlength' => '',
//                            ),
//                            array(
//                                'key' => 'field_5c07dd6ac2642',
//                                'label' => 'Title : border color',
//                                'name' => 'title_border_color',
//                                'type' => 'color_picker',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                            ),
//                            array(
//                                'key' => 'field_5c07ddf6252d1',
//                                'label' => 'Title : border thickness',
//                                'name' => 'title_border_thickness',
//                                'type' => 'number',
//                                'instructions' => '(px)',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => 1,
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                                'min' => '',
//                                'max' => '',
//                                'step' => '',
//                            ),
//                        ),
//                        'min' => '',
//                        'max' => '',
//                    ),
//                    '5bf3387320165' => array(
//                        'key' => '5bf3387320165',
//                        'name' => 'block_background',
//                        'label' => 'Background ',
//                        'display' => 'block',
//                        'sub_fields' => array(
//                            array(
//                                'key' => 'field_5bf3388420166',
//                                'label' => 'Image : background',
//                                'name' => 'background',
//                                'type' => 'image',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'return_format' => 'array',
//                                'preview_size' => 'thumbnail',
//                                'library' => 'all',
//                                'min_width' => '',
//                                'min_height' => '',
//                                'min_size' => '',
//                                'max_width' => '',
//                                'max_height' => '',
//                                'max_size' => '',
//                                'mime_types' => '',
//                            ),
//                        ),
//                        'min' => '',
//                        'max' => '',
//                    ),
//                    '5bf33a6b6feb7' => array(
//                        'key' => '5bf33a6b6feb7',
//                        'name' => 'block_background_text',
//                        'label' => 'Background & Text',
//                        'display' => 'block',
//                        'sub_fields' => array(
//                            array(
//                                'key' => 'field_5bf33a7d6feb8',
//                                'label' => 'Image : background',
//                                'name' => 'background',
//                                'type' => 'image',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'return_format' => 'array',
//                                'preview_size' => 'thumbnail',
//                                'library' => 'all',
//                                'min_width' => '',
//                                'min_height' => '',
//                                'min_size' => '',
//                                'max_width' => '',
//                                'max_height' => '',
//                                'max_size' => '',
//                                'mime_types' => '',
//                            ),
//                            array(
//                                'key' => 'field_5bf33a966feb9',
//                                'label' => 'Text',
//                                'name' => 'wysywig',
//                                'type' => 'wysiwyg',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'tabs' => 'all',
//                                'toolbar' => 'full',
//                                'media_upload' => 0,
//                                'delay' => 0,
//                            ),
//                        ),
//                        'min' => '',
//                        'max' => '',
//                    ),
//                    '5bf411e88d6a7' => array(
//                        'key' => '5bf411e88d6a7',
//                        'name' => 'block_logo_text',
//                        'label' => 'Logo & Text',
//                        'display' => 'block',
//                        'sub_fields' => array(
//                            array(
//                                'key' => 'field_5c07dbcb69a83',
//                                'label' => 'Background : color',
//                                'name' => 'bg_color',
//                                'type' => 'color_picker',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                            ),
//                            array(
//                                'key' => 'field_5bf411fa8d6a8',
//                                'label' => 'Logo',
//                                'name' => 'logo',
//                                'type' => 'image',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '25',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'return_format' => 'array',
//                                'preview_size' => 'thumbnail',
//                                'library' => 'all',
//                                'min_width' => '',
//                                'min_height' => '',
//                                'min_size' => '',
//                                'max_width' => '',
//                                'max_height' => '',
//                                'max_size' => '',
//                                'mime_types' => '',
//                            ),
//                            array(
//                                'key' => 'field_5bf4120d8d6a9',
//                                'label' => 'Text',
//                                'name' => 'wysywyg',
//                                'type' => 'wysiwyg',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '75',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'tabs' => 'all',
//                                'toolbar' => 'full',
//                                'media_upload' => 0,
//                                'delay' => 0,
//                            ),
//                        ),
//                        'min' => '',
//                        'max' => '',
//                    ),
//                    'layout_5bf484d7350f3' => array(
//                        'key' => 'layout_5bf484d7350f3',
//                        'name' => 'block_open_form',
//                        'label' => 'Open form',
//                        'display' => 'block',
//                        'sub_fields' => array(
//                            array(
//                                'key' => 'field_5c07dc0769a84',
//                                'label' => 'Background : color',
//                                'name' => 'bg_color',
//                                'type' => 'color_picker',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                            ),
//                            array(
//                                'key' => 'field_5bf484e7350f4',
//                                'label' => 'Text',
//                                'name' => 'wysywyg',
//                                'type' => 'wysiwyg',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'tabs' => 'all',
//                                'toolbar' => 'full',
//                                'media_upload' => 0,
//                                'delay' => 0,
//                            ),
//                            array(
//                                'key' => 'field_5bf4864fe5c0d',
//                                'label' => 'Link : text',
//                                'name' => 'link_text',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                                'maxlength' => '',
//                            ),
//                            array(
//                                'key' => 'field_5bf484f6350f5',
//                                'label' => 'Form : shortcode',
//                                'name' => 'form_shortcode',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                                'maxlength' => '',
//                            ),
//                            array(
//                                'key' => 'field_5bf48517350f6',
//                                'label' => 'Custom link',
//                                'name' => 'link',
//                                'type' => 'link',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'return_format' => 'array',
//                            ),
//                        ),
//                        'min' => '',
//                        'max' => '',
//                    ),
//
//                    'layout_5d0a8adbf43e2' => array(
//                        'key' => 'layout_5d0a8adbf43e2',
//                        'name' => 'block_instagram',
//                        'label' => 'Instagram',
//                        'display' => 'block',
//                        'sub_fields' => array(
//                            array(
//                                'key' => 'field_5b3f9f7c4c2bx',
//                                'label' => 'Text',
//                                'name' => 'text',
//                                'type' => 'wysiwyg',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'tabs' => 'all',
//                                'toolbar' => 'full',
//                                'media_upload' => 0,
//                                'delay' => 0,
//                            ),
//                        ),
//                        'min' => '',
//                        'max' => '',
//                    ),
//                ),
//                'button_label' => 'Add a block',
//                'min' => '',
//                'max' => '',
//            ),
//
//        ),
//        'location' => array(
//            array(
//                array(
//                    'param' => 'post_type',
//                    'operator' => '==',
//                    'value' => 'page',
//                ),
//                array(
//                    'param' => 'post_template',
//                    'operator' => '!=',
//                    'value' => 'news',
//                ),
//                array(
//                    'param' => 'post_template',
//                    'operator' => '!=',
//                    'value' => 'events',
//                ),
//            ),
//        ),
//        'menu_order' => 0,
//        'position' => 'normal',
//        'style' => 'default',
//        'label_placement' => 'top',
//        'instruction_placement' => 'label',
//        'hide_on_screen' => array(
//            0 => 'the_content',
//        ),
//        'active' => 1,
//        'description' => '',
//    ));

    acf_add_local_field_group(array(
        'key' => 'group_5b3f9c94ac67b',
        'title' => 'Events',
        'fields' => array(
            array(
                'key' => 'field_5b3f9f7c4c2bd',
                'label' => 'Text',
                'name' => 'event_content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
                'delay' => 0,
            ),
            array(
                'key' => 'field_5b3f9c9d22ff1',
                'label' => 'Date',
                'name' => 'event_date',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b3f9cd222ff2',
                'label' => 'Heure',
                'name' => 'event_time',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b3f9ce122ff3',
                'label' => 'Image',
                'name' => 'event_thumbnail',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_category',
                    'operator' => '==',
                    'value' => 'category:events',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5b3f9c338af5d',
        'title' => 'News',
        'fields' => array(
            array(
                'key' => 'field_5b3f9ef93c12c',
                'label' => 'Texte',
                'name' => 'news_content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
                'delay' => 0,
            ),
            array(
                'key' => 'field_5b3f9c65c8bc1',
                'label' => 'Date',
                'name' => 'news_date',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b3f9c74c8bc2',
                'label' => 'Image',
                'name' => 'news_thumbnail',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_category',
                    'operator' => '==',
                    'value' => 'category:news',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5bf42508a8316',
        'title' => 'Page menu',
        'fields' => array(
            array(
                'key' => 'field_5bf42510330d1',
                'label' => 'Title',
                'name' => 'menu_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5bf42526330d2',
                'label' => 'Text',
                'name' => 'menu_wysywyg',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
                'delay' => 0,
            ),
            array(
                'key' => 'field_5bf42535330d3',
                'label' => 'Image at the bottom',
                'name' => 'menu_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_template',
                    'operator' => '==',
                    'value' => 'menu',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5b2185dd92c94',
        'title' => 'Company Informations',
        'fields' => array(
            array(
                'key' => 'field_5b2185dd9d165',
                'label' => 'Contact info',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5b2185dd9d211',
                'label' => 'Informations (more)',
                'name' => 'cw_contact_infos',
                'type' => 'checkbox',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'Phone #2' => 'Phone #2',
                    'Fax' => 'Fax',
                    'Opening hours' => 'Opening hours',
                    'Opening hours list' => 'Opening hours list',
                    'Google map' => 'Google map',
                ),
                'allow_custom' => 0,
                'save_custom' => 0,
                'default_value' => array(
                    0 => 'Phone #1',
                    1 => 'Email',
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5b2185dd9d2d0',
                'label' => 'Phone #1',
                'name' => 'cw_contact_phone01',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d3a6',
                'label' => 'Phone #2',
                'name' => 'cw_contact_phone02',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b2185dd9d211',
                            'operator' => '==',
                            'value' => 'Phone #2',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d44f',
                'label' => 'Email',
                'name' => 'cw_contact_email',
                'type' => 'email',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d53b',
                'label' => 'Fax',
                'name' => 'cw_contact_fax',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b2185dd9d211',
                            'operator' => '==',
                            'value' => 'Fax',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d5e7',
                'label' => 'Adresse FR',
                'name' => 'cw_contact_adress_fr',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d6be',
                'label' => 'Adress EN',
                'name' => 'cw_contact_adress_en',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d779',
                'label' => 'Ville',
                'name' => 'cw_contact_town_fr',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d825',
                'label' => 'Town',
                'name' => 'cw_contact_town_en',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d8fb',
                'label' => 'Province',
                'name' => 'cw_contact_province',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9da73',
                'label' => 'Postal code',
                'name' => 'cw_contact_postal_code',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9dbbc',
                'label' => 'Heures d\'ouverture',
                'name' => 'cw_contact_opening_fr',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b2185dd9d211',
                            'operator' => '==',
                            'value' => 'Opening hours',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9dcdb',
                'label' => 'Opening hours',
                'name' => 'cw_contact_opening_en',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b2185dd9d211',
                            'operator' => '==',
                            'value' => 'Opening hours',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9ddc0',
                'label' => 'Heures d\'ouvertures liste',
                'name' => 'cw_contact_opening_list_fr',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b2185dd9d211',
                            'operator' => '==',
                            'value' => 'Opening hours list',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Ajouter une journée',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5b2185dddf607',
                        'label' => 'Jour',
                        'name' => 'day',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5b2185dddf64c',
                        'label' => 'Heure',
                        'name' => 'time',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5b2185dd9df02',
                'label' => 'Opening hour list',
                'name' => 'cw_contact_opening_list_en',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b2185dd9d211',
                            'operator' => '==',
                            'value' => 'Opening hours list',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add a day',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5b2185dde880e',
                        'label' => 'Day',
                        'name' => 'day',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5b2185dde8852',
                        'label' => 'Time',
                        'name' => 'time',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5b2185dd9e01a',
                'label' => 'Google Map',
                'name' => 'cw_contact_google_map',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b2185dd9d211',
                            'operator' => '==',
                            'value' => 'Google map',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5b2185dd9cfd4',
                'label' => 'Copyrights FR',
                'name' => 'cw_branding_copyrights_fr',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d08f',
                'label' => 'Copyrights EN',
                'name' => 'cw_branding_copyrights_en',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9e0fb',
                'label' => 'Social medias',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5b2185dd9e2e5',
                'label' => 'Facebook',
                'name' => 'cw_social_facebook',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5b2185dd9e39e',
                'label' => 'Twitter',
                'name' => 'cw_social_twitter',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5b2185dd9e44d',
                'label' => 'Instagram',
                'name' => 'cw_social_instagram',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5b2185dd9e53a',
                'label' => 'Trip advisor',
                'name' => 'cw_social_trip_advisor',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5bf48b26f3a0f',
                'label' => 'Youtube',
                'name' => 'cw_social_youtube',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5b218e87e3482',
                'label' => 'For developers',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5b218e98e3483',
                'label' => 'Click to copy code in clipboard',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => 'instruction-main-ctn',
                ),
                'message' => '<h1></h1>
<div class="sections-main-ctn">
	 
	 <div class="section-ctn">
				<h2>Contact information </h2>
				<ul class="section">
						 <li><input type="text" value="$contact[\'phone01\']"></li>
						 <li>Use for href <input type="text" value="$contact[\'phone01_href\']"></li>
						 <li><input type="text" value="$contact[\'phone02\']"></li>
						 <li>Use for href<input type="text" value="$contact[\'phone02_href\']"></li>
						 <li><input type="text" value="$contact[\'email\']"></li>
						 <li><input type="text" value="$contact[\'fax\']"></li>
						 <li><input type="text" value="$contact[\'adress_fr\']"></li>
						 <li><input type="text" value="$contact[\'adress_en\']"></li>
						 <li><input type="text" value="$contact[\'town_fr\']"></li>
						 <li><input type="text" value="$contact[\'town_en\']"></li>
						 <li><input type="text" value="$contact[\'province_fr\']"></li>
						 <li><input type="text" value="$contact[\'province_en\']"></li>
						 <li><input type="text" value="$contact[\'postal_code\']"></li>
						 <li><input type="text" value="$contact[\'opening_fr\']"></li>
						 <li><input type="text" value="$contact[\'opening_en\']"></li>
						 <li><input type="text" value="$contact[\'opening_list_fr\']"></li>
						 <li><input type="text" value="$contact[\'opening_list_en\']"></li>
						 <li><input type="text" value="$contact[\'google_map\']"></li>
				</ul>
	 </div>
<div class="section-ctn">
				<h2>Social media </h2>
				<ul class="section">
						 <li><input type="text" value="$social[\'facebook\']"></li>
						 <li><input type="text" value="$social[\'twitter\']"></li>
						 <li><input type="text" value="$social[\'instagram\']"></li>
						 <li><input type="text" value="$social[\'trip_advisor\']"></li>
				</ul>
	 </div>
</div>',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'company-informations',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5bf3448ad0b6d',
        'title' => 'Page Booking',
        'fields' => array(
            array(
                'key' => 'field_5bf422a2387d5',
                'label' => 'Iframe URL',
                'name' => 'booking_iframe_url',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_template',
                    'operator' => '==',
                    'value' => 'booking',
                ),
            ),
        ),
        'menu_order' => 1,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => 1,
        'description' => '',
    ));

endif;