<?php

// if( function_exists('acf_add_local_field_group') ):
//
// acf_add_local_field_group(array(
// 	'key' => 'group_5bf2b42e0d67d',
// 	'title' => 'Blocks',
// 	'fields' => array(
// 		array(
// 			'key' => 'field_5bf2b4d429f3a',
// 			'label' => 'Blocks',
// 			'name' => 'blocks',
// 			'type' => 'flexible_content',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'layouts' => array(
// 				'layout_5e2ceae19a9b6' => array(
// 					'key' => 'layout_5e2ceae19a9b6',
// 					'name' => 'block_background',
// 					'label' => 'Background',
// 					'display' => 'block',
// 					'sub_fields' => array(
// 						array(
// 							'key' => 'field_5e2cef6a24000',
// 							'label' => 'Content',
// 							'name' => '',
// 							'type' => 'tab',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'placement' => 'top',
// 							'endpoint' => 0,
// 						),
// 						array(
// 							'key' => 'field_5e2cf2e44dc4b',
// 							'label' => 'Options',
// 							'name' => 'block_options',
// 							'type' => 'button_group',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '60',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array(
// 								'bg-only' => 'Image only',
// 								'bg-title' => 'Image	& Title',
// 								'bg-text' => 'Image & Text',
// 								'bgColor-title' => 'Color & Title',
// 								'bgColor-text' => 'Color & Text',
// 							),
// 							'allow_null' => 0,
// 							'default_value' => '',
// 							'layout' => 'horizontal',
// 							'return_format' => 'value',
// 						),
//                         array(
// 							'key' => 'field_5c81dsf2650ecb1',
// 							'label' => 'Height(vh)',
// 							'name' => 'height',
// 							'type' => 'number',
// 							'instructions' => 'Between 0 - 100',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '40',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '60',
// 							'placeholder' => 'default: 60',
// 							'prepend' => '',
// 							'append' => '',
// 							'min' => '0',
// 							'max' => '100',
// 							'step' => '',
// 						),
// 						array(
// 							'key' => 'field_5e2ceae19a9b7',
// 							'label' => 'Background : Image',
// 							'name' => 'background',
// 							'type' => 'image',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => array(
// 								array(
// 									array(
// 										'field' => 'field_5e2cf2e44dc4b',
// 										'operator' => '==',
// 										'value' => 'bg-only',
// 									),
// 								),
// 								array(
// 									array(
// 										'field' => 'field_5e2cf2e44dc4b',
// 										'operator' => '==',
// 										'value' => 'bg-title',
// 									),
// 								),
// 								array(
// 									array(
// 										'field' => 'field_5e2cf2e44dc4b',
// 										'operator' => '==',
// 										'value' => 'bg-text',
// 									),
// 								),
// 							),
// 							'wrapper' => array(
// 								'width' => '20',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'return_format' => 'array',
// 							'preview_size' => 'thumbnail',
// 							'library' => 'all',
// 							'min_width' => '',
// 							'min_height' => '',
// 							'min_size' => '',
// 							'max_width' => '',
// 							'max_height' => '',
// 							'max_size' => '',
// 							'mime_types' => '',
// 						),
// 						array(
// 							'key' => 'field_5e2cf68b06e8d',
// 							'label' => 'Parallax',
// 							'name' => 'parallax',
// 							'type' => 'true_false',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => array(
// 								array(
// 									array(
// 										'field' => 'field_5e2ceae19a9b7',
// 										'operator' => '!=empty',
// 									),
// 								),
// 							),
// 							'wrapper' => array(
// 								'width' => '10',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'message' => '',
// 							'default_value' => 0,
// 							'ui' => 0,
// 							'ui_on_text' => '',
// 							'ui_off_text' => '',
// 						),
// 						array(
// 							'key' => 'field_5e2ceae19a9b9',
// 							'label' => 'Overlay : color',
// 							'name' => 'overlay_color',
// 							'type' => 'color_picker',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => array(
// 								array(
// 									array(
// 										'field' => 'field_5e2ceae19a9b7',
// 										'operator' => '!=empty',
// 									),
// 								),
// 							),
// 							'wrapper' => array(
// 								'width' => '20',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 						),
// 						array(
// 							'key' => 'field_5e2ceae19a9ba',
// 							'label' => 'Overlay : opacity',
// 							'name' => 'overlay_opacity',
// 							'type' => 'range',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => array(
// 								array(
// 									array(
// 										'field' => 'field_5e2ceae19a9b7',
// 										'operator' => '!=empty',
// 									),
// 								),
// 							),
// 							'wrapper' => array(
// 								'width' => '30',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'min' => '',
// 							'max' => 1,
// 							'step' => '0.1',
// 							'prepend' => '',
// 							'append' => '',
// 						),
// 						array(
// 							'key' => 'field_5e2cec8662978',
// 							'label' => 'Background : Color',
// 							'name' => 'background_color',
// 							'type' => 'color_picker',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => array(
// 								array(
// 									array(
// 										'field' => 'field_5e2cf2e44dc4b',
// 										'operator' => '==',
// 										'value' => 'bgColor-title',
// 									),
// 								),
// 								array(
// 									array(
// 										'field' => 'field_5e2cf2e44dc4b',
// 										'operator' => '==',
// 										'value' => 'bgColor-text',
// 									),
// 								),
// 							),
// 							'wrapper' => array(
// 								'width' => '25',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 						),
// 						array(
// 							'key' => 'field_5e2ceae19a9b8',
// 							'label' => 'Title',
// 							'name' => 'title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => array(
// 								array(
// 									array(
// 										'field' => 'field_5e2cf2e44dc4b',
// 										'operator' => '==',
// 										'value' => 'bg-title',
// 									),
// 								),
// 								array(
// 									array(
// 										'field' => 'field_5e2cf2e44dc4b',
// 										'operator' => '==',
// 										'value' => 'bgColor-title',
// 									),
// 								),
// 							),
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 						),
// 						array(
// 							'key' => 'field_5e2d04644eedc',
// 							'label' => 'Text : background color',
// 							'name' => 'text_background_color',
// 							'type' => 'color_picker',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => array(
// 								array(
// 									array(
// 										'field' => 'field_5e2cf2e44dc4b',
// 										'operator' => '==',
// 										'value' => 'bg-text',
// 									),
// 								),
// 							),
// 							'wrapper' => array(
// 								'width' => '20',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 						),
// 						array(
// 							'key' => 'field_5e2cec6e62977',
// 							'label' => 'Text',
// 							'name' => 'text',
// 							'type' => 'wysiwyg',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => array(
// 								array(
// 									array(
// 										'field' => 'field_5e2cf2e44dc4b',
// 										'operator' => '==',
// 										'value' => 'bg-text',
// 									),
// 								),
// 								array(
// 									array(
// 										'field' => 'field_5e2cf2e44dc4b',
// 										'operator' => '==',
// 										'value' => 'bgColor-text',
// 									),
// 								),
// 							),
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'tabs' => 'all',
// 							'toolbar' => 'full',
// 							'media_upload' => 0,
// 							'delay' => 0,
// 						),
// 						array(
// 							'key' => 'field_5e2f42b608e3d',
// 							'label' => 'Animate',
// 							'name' => 'animate',
// 							'type' => 'clone',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'clone' => array(
// 								0 => 'group_5e2f40d7f2970',
// 							),
// 							'display' => 'seamless',
// 							'layout' => 'block',
// 							'prefix_label' => 0,
// 							'prefix_name' => 0,
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
// 				'layout_5d0b96430bbea' => array(
// 					'key' => 'layout_5d0b96430bbea',
// 					'name' => 'block_image_text',
// 					'label' => 'Image & Text',
// 					'display' => 'block',
// 					'sub_fields' => array(
// 						array(
// 							'key' => 'field_5e2f432fd0a16',
// 							'label' => 'Content',
// 							'name' => '',
// 							'type' => 'tab',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'placement' => 'top',
// 							'endpoint' => 0,
// 						),
// 						array(
// 							'key' => 'field_5d0b96600bbee',
// 							'label' => 'Layout',
// 							'name' => 'layout',
// 							'type' => 'button_group',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '50',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array(
// 								'default' => '50% / 50%',
// 								'image-75' => 'Image 75%',
// 								'text-75' => 'Text 75%',
// 								'boxed' => 'Boxed',
// 							),
// 							'allow_null' => 0,
// 							'default_value' => '',
// 							'layout' => 'horizontal',
// 							'return_format' => 'value',
// 						),
// 						array(
// 							'key' => 'field_5d0b96cd0bbef',
// 							'label' => 'Reverse',
// 							'name' => 'reverse',
// 							'type' => 'true_false',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '25',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'message' => '',
// 							'default_value' => 0,
// 							'ui' => 0,
// 							'ui_on_text' => '',
// 							'ui_off_text' => '',
// 						),
// 						array(
// 							'key' => 'field_5d0b96430bbeb',
// 							'label' => 'Background : color',
// 							'name' => 'bg_color',
// 							'type' => 'color_picker',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '25',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 						),
// 						array(
// 							'key' => 'field_5d0b96430bbec',
// 							'label' => 'Images',
// 							'name' => 'images',
// 							'type' => 'gallery',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'return_format' => 'url',
// 							'preview_size' => 'medium',
// 							'insert' => 'append',
// 							'library' => 'all',
// 							'min' => '',
// 							'max' => '',
// 							'min_width' => '',
// 							'min_height' => '',
// 							'min_size' => '',
// 							'max_width' => '',
// 							'max_height' => '',
// 							'max_size' => '',
// 							'mime_types' => '',
// 						),
// 						array(
// 							'key' => 'field_5e31b046a2b98',
// 							'label' => 'Text Background : color',
// 							'name' => 'text_bg_color',
// 							'type' => 'color_picker',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => array(
// 								array(
// 									array(
// 										'field' => 'field_5d0b96600bbee',
// 										'operator' => '==',
// 										'value' => 'boxed',
// 									),
// 								),
// 							),
// 							'wrapper' => array(
// 								'width' => '25',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 						),
// 						array(
// 							'key' => 'field_5d0b96430bbed',
// 							'label' => 'Text',
// 							'name' => 'text',
// 							'type' => 'wysiwyg',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '50',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'tabs' => 'all',
// 							'toolbar' => 'full',
// 							'media_upload' => 0,
// 							'delay' => 0,
// 						),
//                         array(
// 							'key' => 'field_5d0bsdfade3a0d3b47a4708c',
// 							'label' => 'Link',
// 							'name' => 'link',
// 							'type' => 'link',
// 							'instructions' => '',
// 							'required' => 0,
//                             'conditional_logic' => array(
// 								array(
// 									array(
// 										'field' => 'field_5d0b96600bbee',
// 										'operator' => '==',
// 										'value' => 'boxed',
// 									),
// 								),
// 							),
// 							'wrapper' => array(
// 								'width' => '25',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'return_format' => 'array',
// 						),
// 						array(
// 							'key' => 'field_5e2f42e6e9e8b',
// 							'label' => 'Animate',
// 							'name' => 'animate',
// 							'type' => 'clone',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'clone' => array(
// 								0 => 'group_5e2f40d7f2970',
// 							),
// 							'display' => 'seamless',
// 							'layout' => 'block',
// 							'prefix_label' => 0,
// 							'prefix_name' => 0,
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
// 				'5bf2b4dfc6e40' => array(
// 					'key' => '5bf2b4dfc6e40',
// 					'name' => 'block_discover',
// 					'label' => 'Discover',
// 					'display' => 'block',
// 					'sub_fields' => array(
// 						array(
// 							'key' => 'field_5e2f4191556cc',
// 							'label' => 'Content',
// 							'name' => '',
// 							'type' => 'tab',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'placement' => 'top',
// 							'endpoint' => 0,
// 						),
// 						array(
// 							'key' => 'field_5c07db8d8825b',
// 							'label' => 'Background : color',
// 							'name' => 'bg_color',
// 							'type' => 'color_picker',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '33',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 						),
// 						array(
// 							'key' => 'field_5bf2b4ef29f3b',
// 							'label' => 'Logo',
// 							'name' => 'logo',
// 							'type' => 'image',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '33',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'return_format' => 'array',
// 							'preview_size' => 'thumbnail',
// 							'library' => 'all',
// 							'min_width' => '',
// 							'min_height' => '',
// 							'min_size' => '',
// 							'max_width' => '',
// 							'max_height' => '',
// 							'max_size' => '',
// 							'mime_types' => '',
// 						),
// 						array(
// 							'key' => 'field_5c8112650ecb1',
// 							'label' => 'Logo : width (px)',
// 							'name' => 'logo_width',
// 							'type' => 'number',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '33',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'min' => '',
// 							'max' => '',
// 							'step' => '',
// 						),
// 						array(
// 							'key' => 'field_5bf2b45d3b8fc',
// 							'label' => 'Text',
// 							'name' => 'text',
// 							'type' => 'wysiwyg',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'tabs' => 'all',
// 							'toolbar' => 'full',
// 							'media_upload' => 0,
// 							'delay' => 0,
// 						),
// 						array(
// 							'key' => 'field_5bf2b47a4708c',
// 							'label' => 'Discover Link : left',
// 							'name' => 'link_left',
// 							'type' => 'link',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '50',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'return_format' => 'array',
// 						),
// 						array(
// 							'key' => 'field_5bf2b4a64708d',
// 							'label' => 'Discover Link : right',
// 							'name' => 'link_right',
// 							'type' => 'link',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '50',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'return_format' => 'array',
// 						),
// 						array(
// 							'key' => 'field_5e2f412e3a3a1',
// 							'label' => 'Animate',
// 							'name' => 'animate',
// 							'type' => 'clone',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'clone' => array(
// 								0 => 'group_5e2f40d7f2970',
// 							),
// 							'display' => 'seamless',
// 							'layout' => 'block',
// 							'prefix_label' => 0,
// 							'prefix_name' => 0,
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
//
// 				'layout_5bf484d7350f3' => array(
// 					'key' => 'layout_5bf484d7350f3',
// 					'name' => 'block_open_form',
// 					'label' => 'Open form',
// 					'display' => 'block',
// 					'sub_fields' => array(
// 						array(
// 							'key' => 'field_5e319d9f5c0ab',
// 							'label' => 'Content',
// 							'name' => '',
// 							'type' => 'tab',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'placement' => 'top',
// 							'endpoint' => 0,
// 						),
// 						array(
// 							'key' => 'field_5c07dc0769a84',
// 							'label' => 'Background : color',
// 							'name' => 'bg_color',
// 							'type' => 'color_picker',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 						),
// 						array(
// 							'key' => 'field_5bf484e7350f4',
// 							'label' => 'Text',
// 							'name' => 'text',
// 							'type' => 'wysiwyg',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'tabs' => 'all',
// 							'toolbar' => 'full',
// 							'media_upload' => 0,
// 							'delay' => 0,
// 						),
// 						array(
// 							'key' => 'field_5bf484f6350f5',
// 							'label' => 'Form : shortcode',
// 							'name' => 'form_shortcode',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '33',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 						),
// 						array(
// 							'key' => 'field_5bf4864fe5c0d',
// 							'label' => 'Link Form : text',
// 							'name' => 'link_text',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '33',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 						),
// 						array(
// 							'key' => 'field_5bf48517350f6',
// 							'label' => 'Custom link',
// 							'name' => 'link',
// 							'type' => 'link',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '33',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'return_format' => 'array',
// 						),
// 						array(
// 							'key' => 'field_5e319d8c5c0aa',
// 							'label' => 'Animate',
// 							'name' => 'animate',
// 							'type' => 'clone',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'clone' => array(
// 								0 => 'group_5e2f40d7f2970',
// 							),
// 							'display' => 'seamless',
// 							'layout' => 'block',
// 							'prefix_label' => 0,
// 							'prefix_name' => 0,
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
// 				'layout_5d0a8adbf43e2' => array(
// 					'key' => 'layout_5d0a8adbf43e2',
// 					'name' => 'block_instagram',
// 					'label' => 'Instagram',
// 					'display' => 'block',
// 					'sub_fields' => array(
// 						array(
// 							'key' => 'field_5d0a8b2cf43e3',
// 							'label' => 'Hashtag',
// 							'name' => 'hashtag',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 						),
// 						array(
// 							'key' => 'field_5d0a8b48f43e4',
// 							'label' => 'Instagram shortcode',
// 							'name' => 'instagram_shortcode',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
//                 'layout_5e4438e777dd95' => array(
// 					'key' => 'layout_5e4438xx777795',
// 					'name' => 'block_dropdown',
// 					'label' => 'Dropdown',
// 					'display' => 'block',
// 					'sub_fields' => array(
//                         array(
// 							'key' => 'field_5c07dcdsf69a84',
// 							'label' => 'Background : color',
// 							'name' => 'bg_color',
// 							'type' => 'color_picker',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 						),
// 						array(
// 							'key' => 'field_5e4439667779f',
// 							'label' => 'Title',
// 							'name' => 'title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 						),
// 						array(
// 							'key' => 'field_5e44396b777a0',
// 							'label' => 'Events',
// 							'name' => 'events',
// 							'type' => 'repeater',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'collapsed' => '',
// 							'min' => 0,
// 							'max' => 0,
// 							'layout' => 'table',
// 							'button_label' => 'Add an item',
// 							'sub_fields' => array(
// 								array(
// 									'key' => 'field_5e443977777a1',
// 									'label' => 'Name',
// 									'name' => 'name',
// 									'type' => 'text',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array(
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'default_value' => '',
// 									'placeholder' => '',
// 									'prepend' => '',
// 									'append' => '',
// 									'maxlength' => '',
// 								),
// 								array(
// 									'key' => 'field_5e443981777a2',
// 									'label' => 'Description',
// 									'name' => 'description',
// 									'type' => 'wysiwyg',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array(
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'default_value' => '',
// 									'tabs' => 'all',
// 									'toolbar' => 'full',
// 									'media_upload' => 0,
// 									'delay' => 0,
// 								),
// 								array(
// 									'key' => 'field_5e443997777a3',
// 									'label' => 'Image',
// 									'name' => 'image',
// 									'type' => 'image',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array(
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'return_format' => 'array',
// 									'preview_size' => 'medium',
// 									'library' => 'all',
// 									'min_width' => '',
// 									'min_height' => '',
// 									'min_size' => '',
// 									'max_width' => '',
// 									'max_height' => '',
// 									'max_size' => '',
// 									'mime_types' => '',
// 								),
// 							),
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
// 				'layout_5d0baacc3a0d0' => array(
// 					'key' => 'layout_5d0baacc3a0d0',
// 					'name' => 'block_icons_text',
// 					'label' => 'Icons & Text',
// 					'display' => 'block',
// 					'sub_fields' => array(
// 						array(
// 							'key' => 'field_5e31a288a5f15',
// 							'label' => 'Content',
// 							'name' => '',
// 							'type' => 'tab',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'placement' => 'top',
// 							'endpoint' => 0,
// 						),
// 						array(
// 							'key' => 'field_5d0baa5a3a0cd',
// 							'label' => 'Icon : 01',
// 							'name' => 'icon01_grp',
// 							'type' => 'group',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '25',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'layout' => 'block',
// 							'sub_fields' => array(
// 								array(
// 									'key' => 'field_5d0baa763a0ce',
// 									'label' => 'Icon',
// 									'name' => 'icon',
// 									'type' => 'image',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array(
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'return_format' => 'array',
// 									'preview_size' => 'medium',
// 									'library' => 'all',
// 									'min_width' => '',
// 									'min_height' => '',
// 									'min_size' => '',
// 									'max_width' => '',
// 									'max_height' => '',
// 									'max_size' => '',
// 									'mime_types' => '',
// 								),
// 								array(
// 									'key' => 'field_5d0baab93a0cf',
// 									'label' => 'Title',
// 									'name' => 'title',
// 									'type' => 'text',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array(
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'default_value' => '',
// 									'placeholder' => '',
// 									'prepend' => '',
// 									'append' => '',
// 									'maxlength' => '',
// 								),
// 							),
// 						),
// 						array(
// 							'key' => 'field_5d0baade3asdfd1',
// 							'label' => 'Icon : 02',
// 							'name' => 'icon02_grp',
// 							'type' => 'group',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '25',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'layout' => 'block',
// 							'sub_fields' => array(
// 								array(
// 									'key' => 'field_5d0bavvce3a0d2',
// 									'label' => 'Icon',
// 									'name' => 'icon',
// 									'type' => 'image',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array(
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'return_format' => 'array',
// 									'preview_size' => 'medium',
// 									'library' => '',
// 									'min_width' => '',
// 									'min_height' => '',
// 									'min_size' => '',
// 									'max_width' => '',
// 									'max_height' => '',
// 									'max_size' => '',
// 									'mime_types' => '',
// 								),
// 								array(
// 									'key' => 'field_5d0bsdfade3a0d3',
// 									'label' => 'Title',
// 									'name' => 'title',
// 									'type' => 'text',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array(
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'default_value' => '',
// 									'placeholder' => '',
// 									'prepend' => '',
// 									'append' => '',
// 									'maxlength' => '',
// 								),
// 							),
// 						),
// 						array(
// 							'key' => 'field_5d0baasdf83a0d4',
// 							'label' => 'Icon : 03',
// 							'name' => 'icon03_grp',
// 							'type' => 'group',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '25',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'layout' => 'block',
// 							'sub_fields' => array(
// 								array(
// 									'key' => 'field_5d0bcccae83a0d5',
// 									'label' => 'Icon',
// 									'name' => 'icon',
// 									'type' => 'image',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array(
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'return_format' => 'array',
// 									'preview_size' => 'medium',
// 									'library' => '',
// 									'min_width' => '',
// 									'min_height' => '',
// 									'min_size' => '',
// 									'max_width' => '',
// 									'max_height' => '',
// 									'max_size' => '',
// 									'mime_types' => '',
// 								),
// 								array(
// 									'key' => 'field_5d0bxaxxe83a0d6',
// 									'label' => 'Title',
// 									'name' => 'title',
// 									'type' => 'text',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array(
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'default_value' => '',
// 									'placeholder' => '',
// 									'prepend' => '',
// 									'append' => '',
// 									'maxlength' => '',
// 								),
// 							),
// 						),
// 						array(
// 							'key' => 'field_5d0baaf03a0d7',
// 							'label' => 'Icon : 04',
// 							'name' => 'icon04_grp',
// 							'type' => 'group',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '25',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'layout' => 'block',
// 							'sub_fields' => array(
// 								array(
// 									'key' => 'field_5d0baaf03a0d8',
// 									'label' => 'Icon',
// 									'name' => 'icon',
// 									'type' => 'image',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array(
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'return_format' => 'array',
// 									'preview_size' => 'medium',
// 									'library' => 'all',
// 									'min_width' => '',
// 									'min_height' => '',
// 									'min_size' => '',
// 									'max_width' => '',
// 									'max_height' => '',
// 									'max_size' => '',
// 									'mime_types' => '',
// 								),
// 								array(
// 									'key' => 'field_5d0baaf03a0d9',
// 									'label' => 'Title',
// 									'name' => 'title',
// 									'type' => 'text',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array(
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'default_value' => '',
// 									'placeholder' => '',
// 									'prepend' => '',
// 									'append' => '',
// 									'maxlength' => '',
// 								),
// 							),
// 						),
// 						array(
// 							'key' => 'field_5d0baaf93a0da',
// 							'label' => 'Text',
// 							'name' => 'text',
// 							'type' => 'wysiwyg',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'tabs' => 'all',
// 							'toolbar' => 'full',
// 							'media_upload' => 0,
// 							'delay' => 0,
// 						),
// 						array(
// 							'key' => 'field_5d0bab0c3a0db',
// 							'label' => 'Call to action',
// 							'name' => 'cta',
// 							'type' => 'link',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'return_format' => 'array',
// 						),
// 						array(
// 							'key' => 'field_5e31a29928a0f',
// 							'label' => 'Animate',
// 							'name' => 'animate',
// 							'type' => 'clone',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'clone' => array(
// 								0 => 'group_5e2f40d7f2970',
// 							),
// 							'display' => 'seamless',
// 							'layout' => 'block',
// 							'prefix_label' => 0,
// 							'prefix_name' => 0,
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
//
//                 'layout_5e72300c836e4' => array(
// 					'key' => 'layout_5e72300c836e4',
// 					'name' => 'block_counter',
// 					'label' => 'Counter',
// 					'display' => 'block',
// 					'sub_fields' => array(
//                         array(
// 							'key' => 'field_5d0bfvp6430bbeb',
// 							'label' => 'Background : color',
// 							'name' => 'bg_color',
// 							'type' => 'color_picker',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '50',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 						),
//                         array(
//                             'key' => 'field_5e7fcccc3028836e6',
//                             'label' => 'Speed',
//                             'name' => 'speed',
//                             'type' => 'number',
//                             'instructions' => '',
//                             'required' => 0,
//                             'conditional_logic' => 0,
//                             'wrapper' => array(
//                                 'width' => '33',
//                                 'class' => '',
//                                 'id' => '',
//                             ),
//                             'default_value' => '5',
//                             'placeholder' => '',
//                             'prepend' => '',
//                             'append' => '',
//                             'min' => '0',
//                             'max' => '1000',
//                             'step' => '',
//                         ),
//
// 						array(
// 							'key' => 'field_5e72305f836e8',
// 							'label' => 'Title',
// 							'name' => 'title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 						),
// 						array(
// 							'key' => 'field_5e723015836e5',
// 							'label' => 'Counters',
// 							'name' => 'counter_rpt',
// 							'type' => 'repeater',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'collapsed' => '',
// 							'min' => 0,
// 							'max' => 4,
// 							'layout' => 'table',
// 							'button_label' => 'Add counter',
// 							'sub_fields' => array(
// 								array(
// 									'key' => 'field_5e723028836e6',
// 									'label' => 'Number',
// 									'name' => 'number_of',
// 									'type' => 'number',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array(
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'default_value' => '',
// 									'placeholder' => '',
// 									'prepend' => '',
// 									'append' => '',
// 									'min' => '0',
// 									'max' => '',
// 									'step' => '',
// 								),
// 								array(
// 									'key' => 'field_5e723046836e7',
// 									'label' => 'Title',
// 									'name' => 'title',
// 									'type' => 'text',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array(
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'default_value' => '',
// 									'placeholder' => '',
// 									'prepend' => '',
// 									'append' => '',
// 									'maxlength' => '',
// 								),
//
// 							),
//
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
//
// 				'layout_5d362094c40ea' => array(
// 					'key' => 'layout_5d362094c40ea',
// 					'name' => 'block_iframe',
// 					'label' => 'iframe',
// 					'display' => 'block',
// 					'sub_fields' => array(
// 						array(
// 							'key' => 'field_5d3620b0c40eb',
// 							'label' => 'Iframe',
// 							'name' => 'iframe_url',
// 							'type' => 'url',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 						),
// 						array(
// 							'key' => 'field_5d405e9af1acf',
// 							'label' => 'Iframe : Height',
// 							'name' => 'iframe_height',
// 							'type' => 'number',
// 							'instructions' => 'height in px',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '100vh',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'min' => '',
// 							'max' => '',
// 							'step' => '',
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
// 			),
// 			'button_label' => 'Add a block',
// 			'min' => '',
// 			'max' => '',
// 		),
// 	),
// 	'location' => array(
// 		array(
// 			array(
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'page',
// 			),
// 		),
// 	),
// 	'menu_order' => 3,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => array(
// 		0 => 'the_content',
// 		1 => 'discussion',
// 		2 => 'comments',
// 		3 => 'revisions',
// 		4 => 'send-trackbacks',
// 	),
// 	'active' => true,
// 	'description' => '',
// ));

//endif;
