<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5b2185dd92c94',
        'title' => 'Company Informations',
        'fields' => array(
            array(
                'key' => 'field_5b2185dd9d165',
                'label' => 'Contact info',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5b2185dd9d2d0',
                'label' => 'Phone #1',
                'name' => 'contact_phone01',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d3a6',
                'label' => 'Phone #2',
                'name' => 'contact_phone02',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d44f',
                'label' => 'Email',
                'name' => 'contact_email',
                'type' => 'email',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d53b',
                'label' => 'Fax',
                'name' => 'contact_fax',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d5e7',
                'label' => 'Adresse[FR]',
                'name' => 'contact_adress_fr',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d6be',
                'label' => 'Adress[EN]',
                'name' => 'contact_adress_en',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d779',
                'label' => 'Ville',
                'name' => 'contact_city_fr',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d825',
                'label' => 'City',
                'name' => 'contact_city_en',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9d8fb',
                'label' => 'Province',
                'name' => 'contact_province',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2185dd9da73',
                'label' => 'Postal code',
                'name' => 'contact_postal_code',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),

            array(
                'key' => 'field_5b2185dd9ddc0',
                'label' => 'Heures d\'ouvertures[FR]',
                'name' => 'contact_opening_list_fr',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Ajouter une journée',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5b2185dddf607',
                        'label' => 'Jour',
                        'name' => 'day',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5b2185dddf64c',
                        'label' => 'Heure',
                        'name' => 'time',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5b2185dd9df02',
                'label' => 'Opening hour[EN]',
                'name' => 'contact_opening_list_en',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add a day',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5b2185dde880e',
                        'label' => 'Day',
                        'name' => 'day',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5b2185dde8852',
                        'label' => 'Time',
                        'name' => 'time',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5b2185dd9e0fb',
                'label' => 'Social medias',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5b2185dd9e2e5',
                'label' => 'Facebook',
                'name' => 'social_facebook',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5b2185dd9e39e',
                'label' => 'Twitter',
                'name' => 'social_twitter',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5b2185dd9e44d',
                'label' => 'Instagram',
                'name' => 'social_instagram',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5b2185dd9e53a',
                'label' => 'Trip advisor',
                'name' => 'social_trip_advisor',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5bf48b26f3a0f',
                'label' => 'Youtube',
                'name' => 'social_youtube',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            // array(
            //     'key' => 'field_5b218e87e3482',
            //     'label' => 'For developers',
            //     'name' => '',
            //     'type' => 'tab',
            //     'instructions' => '',
            //     'required' => 0,
            //     'conditional_logic' => 0,
            //     'wrapper' => array(
            //         'width' => '',
            //         'class' => '',
            //         'id' => '',
            //     ),
            //     'placement' => 'left',
            //     'endpoint' => 0,
            // ),
//             array(
//                 'key' => 'field_5b218e98e3483',
//                 'label' => 'Click to copy code in clipboard',
//                 'name' => '',
//                 'type' => 'message',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => 'instruction-main-ctn',
//                 ),
//                 'message' => '<h1></h1>
// <div class="sections-main-ctn">
//
// 	 <div class="section-ctn">
// 				<h2>Contact information </h2>
// 				<ul class="section">
// 						 <li><input type="text" value="$contact[\'phone01\']"></li>
// 						 <li>Use for href <input type="text" value="$contact[\'phone01_href\']"></li>
// 						 <li><input type="text" value="$contact[\'phone02\']"></li>
// 						 <li>Use for href<input type="text" value="$contact[\'phone02_href\']"></li>
// 						 <li><input type="text" value="$contact[\'email\']"></li>
// 						 <li><input type="text" value="$contact[\'fax\']"></li>
// 						 <li><input type="text" value="$contact[\'adress_fr\']"></li>
// 						 <li><input type="text" value="$contact[\'adress_en\']"></li>
// 						 <li><input type="text" value="$contact[\'town_fr\']"></li>
// 						 <li><input type="text" value="$contact[\'town_en\']"></li>
// 						 <li><input type="text" value="$contact[\'province_fr\']"></li>
// 						 <li><input type="text" value="$contact[\'province_en\']"></li>
// 						 <li><input type="text" value="$contact[\'postal_code\']"></li>
// 						 <li><input type="text" value="$contact[\'opening_fr\']"></li>
// 						 <li><input type="text" value="$contact[\'opening_en\']"></li>
// 						 <li><input type="text" value="$contact[\'opening_list_fr\']"></li>
// 						 <li><input type="text" value="$contact[\'opening_list_en\']"></li>
// 						 <li><input type="text" value="$contact[\'google_map\']"></li>
// 				</ul>
// 	 </div>
// <div class="section-ctn">
// 				<h2>Social media </h2>
// 				<ul class="section">
// 						 <li><input type="text" value="$social[\'facebook\']"></li>
// 						 <li><input type="text" value="$social[\'twitter\']"></li>
// 						 <li><input type="text" value="$social[\'instagram\']"></li>
// 						 <li><input type="text" value="$social[\'trip_advisor\']"></li>
// 				</ul>
// 	 </div>
// </div>',
//                 'new_lines' => 'wpautop',
//                 'esc_html' => 0,
//             ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'company-informations',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    // acf_add_local_field_group(array(
    //     'key' => 'group_5bf3448ad0b6d',
    //     'title' => 'Page Booking',
    //     'fields' => array(
    //         array(
    //             'key' => 'field_5bf422a2387d5',
    //             'label' => 'Iframe URL',
    //             'name' => 'booking_iframe_url',
    //             'type' => 'url',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'default_value' => '',
    //             'placeholder' => '',
    //         ),
    //     ),
    //     'location' => array(
    //         array(
    //             array(
    //                 'param' => 'post_template',
    //                 'operator' => '==',
    //                 'value' => 'booking',
    //             ),
    //         ),
    //     ),
    //     'menu_order' => 1,
    //     'position' => 'normal',
    //     'style' => 'default',
    //     'label_placement' => 'top',
    //     'instruction_placement' => 'label',
    //     'hide_on_screen' => array(
    //         0 => 'the_content',
    //     ),
    //     'active' => 1,
    //     'description' => '',
    // ));

endif;
